### ISSUE TITLE
Segfault in perfctr after deactivating a core

### ISSUE THREAD

**Issue by woelke** [RRZE-HPC/likwid#119]
I get a segmentation fault in perfctr after deactivating cores.

Server details:
Model: AMD Opteron 6376 Processors (4 Sockets, 8 NUMA nodes and 64 cores)
OS: OpenSuse

How to reproduce:
When all cores are active the perfctr command works fine:
likwid-perfctr -c 0 -g UNC_CPU_REQUEST_TO_MEMORY_LOCAL_LOCAL_CPU_MEM:UPMC0 sleep 2

But when you deactivate an arbitrary core with the subsequent command likwid-perfctr ends up in a segfault.
sudo su -c "echo 0 > /sys/devices/system/cpu/cpu32/online"

**Comment by TomTheBear** [comment]
There are some parts in the code that rely on all CPUs being online. I was able to fix the segfault pretty quickly but there are other parts that behave wrong afterwards. It will be a huge effort to fix this and I will do that when I have to rewrite the topology backend as soon as the new version of hwloc with API changes is out.

**Comment by TomTheBear** [comment]
I did some experiments and I won't add an isonline check. The problem is that the only way is to read the files in sysfs and LIKWID needs it at a fine grain, so it will check the online state at each access. This adds quite some overhead. I cannot think about a reasonable use case where this is needed.
