### ISSUE TITLE
Changing release tags

### ISSUE THREAD

**Issue by michaelkuhn** [RRZE-HPC/likwid#129]
The current practice of changing (pre-)release tags makes it hard to package likwid. Someone added likwid 4.3.0 to Spack and we had to fix the hash a few times already (see https://github.com/spack/spack/pull/6307).

Would you mind reconsidering this? For instance, you could tag release candidates (x.y.z-rc1, x.y.z-rc2 etc.) and only tag a release (x.y.z) once it is final.

**Comment by TomTheBear** [comment]
I only change pre-release tags and not release tags. I can understand that it is annoying to update packages but for me the question arises whether pre-release versions should be packaged at all. That's why they are pre-release.
The 4.3.0 pre-release tag and the update under the same tag was requested by users and they are happy as it is. From my point of view I wouldn't need such a pre-release version at all, it is just work for me to update the tags. The -rcX way would cause even more work because I don't want to have 100 releases/tags in the release/tags list and so I have to delete all -rcX versions/tags manually when publishing the final release.
But I'll think about it.

**Comment by michaelkuhn** [comment]
Thanks for the fast reply! I guess we then have to be a bit more careful not to add pre-release versions to Spack. :-)

**Comment by hahnjo** [comment]
(drive-by comment) The git documentation says you should never retag: https://git-scm.com/docs/git-tag#_on_re_tagging

**Comment by hahnjo** [comment]
btw I just found another source of confusion: Because the branch has the same name as the first tag, GitHub can't differentiate between them. So if you click on the tag `4.3.0`, you'll get the branch instead. That's probably a bug in GitHub but pretty easy to work-around by using unique names (eg `release-4.3` for the branch)
