### ISSUE TITLE
Reset the counters in the marker API

### ISSUE THREAD

**Issue by Ezibenroc** [RRZE-HPC/likwid#131]
I am trying to profile a function that is called in a loop. I would like to get the values of all the events for each iteration of the loop, to study the variability of this function.

Here is a simplified example of what I am doing so far:
```c
#include <stdio.h>
#include <assert.h>
#include <likwid.h>
#include <omp.h>

#define N 1<<20

void my_expensive_function(void) {
    #pragma omp parallel
    {
    for(int i = 0; i < N; i ++) {
        #pragma omp for
        for(int j = 0; j < N; j++) {
        }
    }
    }
}

int main(void) {
    int nb_calls = 5;

// Initialization of Likwid
#ifdef LIKWID_PERFMON
    FILE *likwid_outfile=stdout;
    LIKWID_MARKER_INIT;
    #pragma omp parallel
    {
        LIKWID_MARKER_THREADINIT;
        LIKWID_MARKER_REGISTER("perf_test");
    }
    // we do not handle the multi-group case (yet?)
    assert(perfmon_getNumberOfGroups() == 1);
#endif

    for(int i = 0; i < nb_calls; i++) {
// Starting the measure
#ifdef LIKWID_PERFMON
        #pragma omp parallel
        {
            LIKWID_MARKER_START("perf_test");
        }
#endif
        my_expensive_function();
// Stopping the measure and printing the counters
#ifdef LIKWID_PERFMON
        #pragma omp parallel
        {
            LIKWID_MARKER_STOP("perf_test");
            int nevents = 10;
            double events[10];
            double time;
            int count;
            LIKWID_MARKER_GET("perf_test", &nevents, events, &time, &count);
            int my_thread_id = omp_get_thread_num();
            for(int nthread = 0; nthread < omp_get_num_threads(); nthread++) {
                if(my_thread_id == nthread) {
                    fprintf(likwid_outfile, "%d,%f,%d,%d", i, time, my_thread_id,
                        likwid_getProcessorId());
                    for (int ev = 0; ev < nevents; ev++) {
                        fprintf(likwid_outfile, ",%f", events[ev]);
                    }
                    fprintf(likwid_outfile, "\n");
                }
                #pragma omp barrier
            }
        }
#endif
    }

#ifdef LIKWID_PERFMON
    LIKWID_MARKER_CLOSE;
    if(likwid_outfile != stdout)
        fclose(likwid_outfile);
#endif
    return 0;
}
```

Compilation and execution (put the above code in `mwe.c`):
```sh
gcc -fopenmp mwe.c -O3 -o mwe -DLIKWID_PERFMON -llikwid
likwid-perfctr -C 0 -g CLOCK -m ./mwe
```
The output contains these lines:
```
0,0.131077,0,0,57229321.000000,87256694.000000,86642413.000000,1.119385,0.079102,0.000000
1,0.235265,0,0,114263646.000000,174678046.000000,153226656.000000,2.496887,0.150208,0.000000
2,0.340247,0,0,171335345.000000,261932619.000000,220689964.000000,3.813232,0.219421,0.000000
3,0.446558,0,0,228403486.000000,349158458.000000,287432959.000000,5.195740,0.287537,0.000000
4,0.551457,0,0,285480249.000000,436310554.000000,354167000.000000,6.523499,0.353027,0.000000
```
The fields are respectively the index of the iteration, the time, the thread index, the core index and then all the Likwid events. You can see that the time and the Likwid events are cumulative values, they are increasing at each iteration of the loop.

I would like to have non-cumulative values. Currently, I am post-processing the data in a script, but I am not very satisfied by this solution. The issue is that some Likwid events are not cumulative like this (e.g. the event `TEMP_CORE`), so the post-processing depends on the event, this is tedious and error prone.

I think it would be better to have a macro to reset all the counters to 0, e.g. `LIKWID_MARKER_RESET`.

I tried to move the initialisation/liberation part (`LIKWID_MARKER_{INIT,THREADINIT,CLOSE}`) in the loop, but it did not change the results and I am not sure they are intended to be used like that.

**Comment by TomTheBear** [comment]
This is not the intended use for the MarkerAPI with its aggregation but I understand what and why you want.
There would be multiple ways to get what you want, one option would be the `LIKWID_MARKER_RESET` call you proposed but also `LIKWID_MARKER_GET_LAST` would do the job.
Since the MarkerAPI is just a extension to the normal LIKWID API you can use the later one to get your profiling data or at least a big part of your data.

This is just the part you need to change:
```
#pragma omp parallel
        {
            LIKWID_MARKER_STOP("perf_test");
            int nevents = 0;
            double time;
            int count;
            // No need to fill the events array, so nevents is set to 0
            LIKWID_MARKER_GET("perf_test", &nevents, NULL, &time, &count);
            int my_thread_id = omp_get_thread_num();
            for(int nthread = 0; nthread < omp_get_num_threads(); nthread++) {
                if(my_thread_id == nthread) {
                    fprintf(likwid_outfile, "%d,%f,%d,%d", i, time, my_thread_id,
                        likwid_getProcessorId());
                    for (int ev = 0; ev < perfmon_getNumberOfEvents(0); ev++) {
                        fprintf(likwid_outfile, ",%f", perfmon_getLastResult(0, ev, nthread));
                    }
                    fprintf(likwid_outfile, "\n");
                }
                #pragma omp barrier
            }
        }
```
It is still required to get the time out of the MarkerAPI interface because the normal LIKWID API takes only a single time for all threads and you probably want the runtime per thread, otherwise there is `perfmon_getLastTimeOfGroup(groupid)`. The event data can be read with `perfmon_getLastEvent(groupid, eventid, threadid)` which returns the difference between the last two read calls (or the current value of `TEMP_CORE`), in your case between the reads in `LIKWID_MARKER_START(str)` and `LIKWID_MARKER_STOP(str)`. The group ids start commonly with 0 but you can also get the group id with `perfmon_getIdOfActiveGroup()` to be sure. If pinned with LIKWID, the OpenMP thread ID can also be used as thread ID for LIKWID.
Just as a hint, you can get the derived metrics at that point using `perfmon_getLastMetric(groupid, metricid, threadid)` and `perfmon_getNumberOfMetrics(groupid)`.

**Comment by Ezibenroc** [comment]
Thanks a lot, this works very well.

This is not a big issue if only the values for the time have to be post-processed. My biggest concern was that I could not predict without testing if a given event would be "cumulative", like `CPU_CLK_UNHALTED_CORE`, or not, like `TEMP_CORE`. Now this is simple enough.
