### ISSUE TITLE
Question: using events identified with perfctlr to be used with perf

### ISSUE THREAD

**Issue by yogeshVU** [RRZE-HPC/likwid#140]
How can one use the events identified using the ``` perfctr -e``` use with the linux-perf command list?

example ```INSTR_RETIRED_ANY```  was identified as an event by the ```perfctr -e```, but does not work with the perf stat
```
 perf stat -x , -e INSTR_RETIRED_ANY
invalid or unsupported event: 'INSTR_RETIRED_ANY'
Run 'perf list' for a list of valid events

 usage: perf stat [<options>] [<command>]

    -e, --event <event>   event selector. use 'perf list' to list available events
 
```

**Comment by TomTheBear** [comment]
perf does not know the event names but you can use the hex values printed by LIKWID to create a proper event hex value for perf.
Example LIKWID event (`likwid-perfctr -e` or `likwid-perfctr -E <searchstr>`):
PAGE_WALKER_LOADS_DTLB_L3, 0xBC, 0x14, PMC
Translates for perf in:
`perf stat -e  r14BC <exec>`

So use the second hex value on the LIKWID line (umask) followed by the first hex value (event id). This works only for simple definitions. I have never tried how to add event options like threshold, invert, anythread, etc. to the raw event definitions of perf. The single bits and bit ranges you can you use in the raw event string are probably those in the `/sys/devices/cpu/format/` folder (event id = 0-7, umask = 8-15)
Since you used `INSTR_RETIRED_ANY`: This event exists twice for Intel architectures: as fixed purpose counter and configurable in the common performance monitoring counters. If you use the `instructions` event of perf it (looks like it) uses the performance monitoring counters and I don't know how to tell perf to use the fixed purpose counter.

Moreover, in the gooda project (https://github.com/David-Levinthal/gooda) there are patches to connect perf with libpfm (event library also used by PAPI) so that you can use event names in perf.

**Comment by TomTheBear** [comment]
I added the description to the wiki: https://github.com/RRZE-HPC/likwid/wiki/TutorialLikwidPerf

Can I close this issue? Or you do it when you don't have further questions.

**Comment by yogeshVU** [comment]
This is super cool! thanks for making this part of the wiki..closing issue
