### ISSUE TITLE
errors reading multiple groups

### ISSUE THREAD

**Issue by yogeshVU** [RRZE-HPC/likwid#162]
Cannot read all the groups simultaneously using perfctr

```
likwid-perfctr -g CACHES -g ICACHE -g TLB_INSTR sleep 4 
```

[error_log](https://gist.github.com/yogeshVU/eed26c05380272ee0504efcfe9bd926b)

**Comment by TomTheBear** [comment]
LIKWID does not support automatic multiplexing of eventsets.

You can give multiple eventsets on command line and LIKWID tries to cycle through the eventsets but you get only the measurements of the time the eventset was running. There is nothing like interpolation/extrapolation/scaling for the not-measured values.

With `-T` command line switch you can set the frequency with which the eventsets are switched. The default frequency is 2 seconds. This explains why you get values for the CACHES and the ICACHE group but not for TLB_INSTR. You can also see at "Runtime", that both groups are measured (around) 2 seconds and all values in a group is based on its measurement duration.

Here is the description in the wiki: https://github.com/RRZE-HPC/likwid/wiki/likwid-perfctr#using-multiple-event-sets-or-performance-groups-in-a-single-run
Excerpt from the `likwid-perfctr` man page:
`-T <time between group switches>`
Frequency  to  switch  groups  if multiple are given on commandline, default is 2s. Value is ignored for a single event set and default frequency of 30s is used to catch overflows. The time unit must be given on command line, e.g. 4s, 500ms or 900us.

**Comment by yogeshVU** [comment]
Thanks for clarification.  To extend this further, can one run two instances of the perfctlr for measuring  CACHE group in one instance and ENERGY group in another instance. SO basically 

```
likwid-perfctr -g CACHES -S 5s
likwid-perfctr -g ENERGY -S 5s
```

**Comment by TomTheBear** [comment]
As long as they don't measure the same counters you can do that. But commonly all groups use the fixed-counters (`FIXC0-2`). It should work but ignore the measurements for `FIXC0-2` and derived metrics (e.g. `CPI`), they are probably wrong. The fixed counters should be the only counters used by both, so why not combining the groups by creating your own group and measure everything in a single run?

https://github.com/RRZE-HPC/likwid/wiki/likwid-perfctr#defining-custom-performance-groups

**Comment by yogeshVU** [comment]
Thanks for that suggestion.. I will try to create a custom group using the wiki link you provided.

**Comment by yogeshVU** [comment]
I created a custom file.. and get following error.
(MYGROUP)(https://gist.github.com/yogeshVU/294cad7d1027ee7875c14c928fcb67f6)

(errorFile)[https://gist.github.com/yogeshVU/84f8afa07191f2ec3139bd5acaf20552]

**Comment by yogeshVU** [comment]
Apparently it is something to do with the PMC4-7 numbers. If we just used any PMC0-3 it works fine.. hmmm

**Comment by yogeshVU** [comment]
more info about the hw:
```
--------------------------------------------------------------------------------
CPU name:	Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
CPU type:	Intel Xeon Broadwell EN/EP/EX processor
CPU clock:	2.10 GHz
CPU family:	6
CPU model:	79
CPU short:	broadwellEP
CPU stepping:	1
CPU features:	
--------------------------------------------------------------------------------
PERFMON version:	3
PERFMON number of counters:	8
PERFMON width of counters:	48
PERFMON number of fixed counters:	3
--------------------------------------------------------------------------------

```

**Comment by TomTheBear** [comment]
The PMC4-7 counters have some problems on Broadwell, see relevant specification updates from Intel (BDW116, BDF47, BDW59).
I recommend using the PMC0-3 counters in most cases and use PMC4-7 only if there is no other option.
Nevertheless, I'll take a look as soon as I have a Broadwell system with HyperThreading disabled.

**Comment by yogeshVU** [comment]
Are there any other registers one can use to get more than 4 program counters in a group...? in this particular scenario

**Comment by TomTheBear** [comment]
You can use each register once in a group. Broadwell EP provides quite a lot of counter registers, see `likwid-perfctr -e`.
For core-local events you are limited to the 3 fixed-counters (`FIXC0-2`) and the 4/8 general-purpose counters (`PMC0-3`/`PMC0-7`). You can use the counters `PMC4-7` but test the events whether they really count and the counts seem reasonable, e.g. by programming the same event on one of `PMC0-3` and one of `PMC4-7`. The counts should almost match. In your output, the event `UOPS_RETIRED_ALL` on `PMC6` seems to count but the counts don't look reasonable as core 3,4,5 and 8 don't retire any instruction but uops.

Just as a remark: I don't see any errors in the execution. It clearly states `WARNING`!
Second remark: You use the events `MEM_LOAD_UOPS_RETIRED_L3_ALL` and `MEM_LOAD_UOPS_RETIRED_L3_MISS`. These events undercount up to 20% (BDW85 but not in Xeon E5 v4 specification update) but the ratio should be ok.

**Comment by yogeshVU** [comment]
So if I understand correctly, one will not be able to measure more than 8 registers of L2(since it is local) at once. as in this case:

```
L2_RQSTS_DEMAND_DATA_RD_MISS, 0x24, 0x21, PMC
L2_RQSTS_DEMAND_DATA_RD_HIT, 0x24, 0x41, PMC
L2_RQSTS_RFO_MISS, 0x24, 0x22, PMC
L2_RQSTS_RFO_HIT, 0x24, 0x42, PMC
L2_RQSTS_CODE_RD_MISS, 0x24, 0x24, PMC
L2_RQSTS_CODE_RD_HIT, 0x24, 0x44, PMC
L2_RQSTS_L2_PF_HIT, 0x24, 0x50, PMC
L2_RQSTS_L2_PF_MISS, 0x24, 0x30, PMC
L2_RQSTS_ALL_DEMAND_DATA_RD, 0x24, 0xE1, PMC
L2_RQSTS_ALL_DEMAND_MISS, 0x24, 0x27, PMC
L2_RQSTS_ALL_RFO, 0x24, 0xE2, PMC
L2_RQSTS_ALL_CODE_RD, 0x24, 0xE4, PMC
L2_RQSTS_ALL_DEMAND_REFERENCES, 0x24, 0xE7, PMC
L2_RQSTS_ALL_PF, 0x24, 0xF8, PMC
L2_RQSTS_MISS, 0x24, 0x3F, PMC
L2_RQSTS_REFERENCES, 0x24, 0xFF, PMC
L2_DEMAND_RQST_WB_HIT, 0x27, 0x50, PMC

```

**Comment by TomTheBear** [comment]
I assume you mean 8 events of L2. No you cannot measure more than 8 in a single run. If you want to measure more, you have to do two runs.
But maybe it's not needed: Each lines contains the name, the event id, the umask and the counter specification. The event id of most of your events is `0x24`, so it's the same event group. The umask values differ and in many cases it's not the actual number that matters but the 1-bits in the umask.
So, let's pick two events: `L2_RQSTS_RFO_MISS` (umask `b0010 0010`) and `L2_RQSTS_RFO_HIT` (`b0100 0010`). If you check the umasks you see, that probably the `RFO` bit is `0x02` and the distinction between `MISS` and `HIT` is `0x20` or `0x40`. When checking the others, you get `DEMAND_DATA_RD` is `0x01` and `CODE_RD` is `0x04`. So the `MISS` umask of all three read types is `0x27`. If you check for umask `0x27` you will find `L2_RQSTS_ALL_DEMAND_MISS`. So instead of measuring the three subevents, you can measure this combined event first and see whether it indicates something suspicious before digging deeper by measuring all three events.
Some of these combined events are published by the vendors (like `L2_RQSTS_ALL_DEMAND_MISS`). Some are not published but if it is obvious, I add them and _try_ to give them meaningful names.

**Comment by yogeshVU** [comment]
Thanks for clarification. I am trying to understand if it is an issue(number of events) with likwid tool. Correct me if I am wrong, but can't we measure more number of events using the linux-perf utility and not restricted to 8?

**Comment by TomTheBear** [comment]
It's only partly an issue of likwid itself. The hardware does not provide more registers.

With linux-perf you can measure more than 8 counters because it multiplexes the events on the 4/8 counters. This requires linux-perf to switch events often enough to get reliable data and therefore it checks for a reschedule at every task scheduler run (that's my impression how it works, I didn't read the full linux-perf code). This causes overhead but since it's in the kernel and kernel is allowed to read/write MSRs and PCI registers directly, it's not as high as for LIKWID with its accesses from userspace.

**Comment by yogeshVU** [comment]
Again, thanks for the information!
