### ISSUE TITLE
RAPL domain DRAM for Zen architecture?

### ISSUE THREAD

**Issue by vvsteg** [RRZE-HPC/likwid#181]
Hi!

As far as I see, likwid-powermeter does not provide information about DIMMs power consumption for AMD Epyc CPUs.

According to the AMD uProf User Guide v.1.2, there is only the following relevant counter:

> Average DDR Memory-Controller Power for the sampling period,
> reported in Watts. This Power is an estimated consumption
> value which is calculated based on APU activity levels.
> This value does not include the power consumed by the memory
> DIMMs

Please let me know if it is a general limitation for the Zen architecture? 
Or some workarounds for measuring DIMMs power consumption could be expected in the future?

**Comment by TomTheBear** [comment]
Hi,

after reading the document, I'm pretty sure that you need an extra kernel driver. Basically, this information is provided by the AMD SMU and there is a [presentation](https://events.ccc.de/congress/2014/Fahrplan/system/attachments/2503/original/ccc-final.pdf) how to exploit that system processor but it seems to be a lot of work to integrate it into LIKWID and to find the relevant "counters" in the SMU without documentation.
Moreover, as the document and your text snippet describes, it is not a measurement but some estimation based on the I/O requests or similar and you don't get the full profile because the DIMMs are excluded.

According to the perf_event code for AMD Zen, there are some kind of data fabric counters. Those might contain functionality like reading energy or memory traffic but they are not published and, to my information, the hardware architects don't want to release the information in the future.
So, currently there are no plans to add this feature to LIKWID.

**Comment by vvsteg** [comment]
Thank you for the information and explanation! Anyway, RAPL power data for DIMMs are not very precise... Perhaps, it could be a rationale behind this limitation.

**Comment by TomTheBear** [comment]
That could be a reason but I suggest it's just money. AMD Zen provides RAPL domains for cores and package, both pretty close to the CPU cores which access the registers in the end. Although the memory controllers are also pretty close, the DIMMs are far away and you need hardware to measure the energy consumption there. Both costs money. If AMD would have seen the benefit of real measurements compared to estimations, they would have spend the money. For adjusting core frequencies (one task of the SMU) an estimation of the energy consumption is enough.

**Comment by vvsteg** [comment]
Excuse me, but I do not see your point :)

Intel RAPL power values for DIMMs are estimated values as well. Benchmarks show that they quite approximate but reasonable (e.g. http://web.eece.maine.edu/~vweaver/projects/rapl/2016_memsys_rapl.pdf).

So making similarly would not imply extra hardware for AMD, would it? And the benefit is evident: all the RAPL-based software works seamlessly.

**Comment by TomTheBear** [comment]
My information might be wrong but I remember that Intel RAPL has two modes: estimation and measurement. I heard this quite some time ago, no clue whether this is true or not. [SDM 05/2018 14.9](https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf):
> MSR_PKG_ENERGY_STATUS reports measured actual energy usage
> MSR_PP0_ENERGY_STATUS/MSR_PP1_ENERGY_STATUS report actual energy usage on a power plane
> MSR_DRAM_ENERGY_STATUS reports measured actual energy usage.

Even if the SMU has the hardware, you still need to wire the registers back into the CPU cores to enable RAPL (MSRs on x86). And wires cost a lot (according to some Intel engineer). Moreover, you additionally need wires to get the energy data from the DIMMs because providing only half of the information is probably not what users want. 

> And the benefit is evident: all the RAPL-based software works seamlessly.

With my experience to hardware counting, this will almost never happen. It starts with different energy units per domain while only a single energy unit is machine readable (the other one is a footnote in some specification document) and ends with different domains having the same name but cover something completely different (PP0/PP1 for Uncore or iGPU). Now AMD has introduced the CORE domain which is not available on Intel. Intel, on the other hand, has introduced the SYSTEM domain (with Skylake) which I have never seen to work. PP0 and PP1 are somewhat provided by all Intel architectures but are not officially supported (anymore). And does the PKG domain of AMD's RAPL cover the same units as Intel's RAPL PKG domain? Are they comparable?

**Comment by vvsteg** [comment]
Thank you for an enlightening remarks.

> Are they comparable?

Even in the case when they are not truly comparable, I would say that the usefulness of this machinery is that it provides the possibility to optimise energy efficiency (perhaps, on the basis of not very precise guesstimates).

Actually, with my colleagues we want to deploy [the energy accounting plugin for SLURM](https://link.springer.com/chapter/10.1007/978-3-642-45249-9_7). But neither IPMI sensors is accessible via FreeIPMI on our Supermicro servers, nor RAPL works with DIMMs for Epyc CPUs. So we get stuck :)

**Comment by TomTheBear** [comment]
You're welcome. I totally agree with you that RAPL is useful even if the counts are not 100% correct. 
At least you can read the data of AMD's uProf in the SLURM plugin. Aren't there other sensors (lm-sensors) that could provide you some data?

**Comment by vvsteg** [comment]
As far as I know, lm-sensors can not help in my case...

Just for the completeness, I would like to share the link to the reply I've got from the AMD forum about the power counters:
https://community.amd.com/message/2874564#comment-2874564

**Comment by TomTheBear** [comment]
Thanks for the update.
