### ISSUE TITLE
segfault in access_client.c from null pointer

### ISSUE THREAD

**Issue by jdeters** [RRZE-HPC/likwid#187]
I'm getting a segfault when using the accessDaemon in access_client.c. Specifically, the variable cpuSockets is null in some cases when access_client_read() or access_client_write() are called.

I've attached my debug output for a run of my program.
[out.txt](https://github.com/RRZE-HPC/likwid/files/2511944/out.txt)

**Background**
I'm currently benchmarking a modified Cilk Plus runtime that takes NUMA affects into account. So we are using the MarkerAPI from _within_ the runtime, not user code. We're also 
pinning our workers to cores from within the runtime. I'm unsure of where this behavior is exactly coming from as I did not have this issue when using Likwid 4.2. 

Please let me know if you need any more information.

**Comment by TomTheBear** [comment]
This might happen if the PID detection fails. The communication link with the accessDaemon is not thread-safe so as soon as you add more threads (with different system thread id as the main PID) to the access layer, it opens separate connections for each thread.
In order to allocate the cpuSockets only once, it is done by the main PID but if that fails it is never allocated and you get problems when reading or writing. 

I don't see any problem in your output, you get results for all threads and all CPUs are finalized properly. No read or write errors. Am I missing something?

In 4.2, the cpuSockets array was statically initialized with length MAX_NUM_THREADS. Version 4.3 initializes the array dynamically to reduce memory footprint and to get rid of the MAX_NUM_THREADS define. That might be a reason for your problems and it's almost the only change in the access_client.c file since 4.2.

Do you call LIKWID_MARKER_CLOSE and afterwards LIKWID_MARKER_INIT again?

**Comment by jdeters** [comment]
We are calling LIKWID_MARKER_CLOSE and LIKWID_MARKER_INIT again. We're calling the parallel regions of the code repeatedly for taking measurements and we needed a way to reset LIKWID between rounds. Previously calling LIKWID_MARKER_CLOSE and then immediately calling LIKWID_MARKER_INIT worked fine for us.

**Comment by TomTheBear** [comment]
The values are not set to zero at LIKWID_MARKER_CLOSE (Tested with 4.3.2 and 4.2.1). The counts are aggregated in an extra data structure as the real counter values and the MarkerAPI values are different. This data structure is emptied in the destructor of the MarkerAPI (4.2.1 and 4.3.2), so it doesn't make sense to do CLOSE and INIT. LIKWID_MARKER_CLOSE just writes out a file that is picked up by likwid-perfctr after the application finished to output the data. If it would really close the MarkerAPI (zero all values, cleaning all MarkerAPI data structures), you would just see the last region runs in the output in the end.

Have you used LIKWID 4.2.1 or 4.2.0 where it worked for you?

The easiest way to achieve what you want is to use a new region string for each new measurement iteration. Each new region starts with an empty MarkerAPI data structure.

**Comment by TomTheBear** [comment]
I added a reset function to the MarkerAPI.
Maybe for your case the common API gives you more freedom to do what you want but you have to do some management yourself. The default API would be something like this:
globally call `perfmon_init()`, `perfmon_addEventset(<e.g. from env variable>)`, `perfmon_setupCounters()`, `perfmon_startCounters()` -> `LIKWID_MARKER_INIT`
per-thread call `perfmon_readCountersCpu(cpu_id)`, `perfmon_getLastResult()` or `perfmon_getLastMetric()` and store the results per thread and region as start value ->`LIKWID_MARKER_START `

[yourcode]

per-thread call `perfmon_readCountersCpu(cpu_id)`, `perfmon_getLastResult()` or `perfmon_getLastMetric()` and store the results per thread and region as stop value ->`LIKWID_MARKER_STOP`
globally call `perfmon_stopCounters()` and `perfmon_finalize()` -> `LIKWID_MARKER_CLOSE`

That's basically what the MarkerAPI does. It stores the values in a per-thread hash table with region string as key.

**Comment by jdeters** [comment]
This is extremely helpful! I'll give it a shot and report back if I have any issues.

**Comment by TomTheBear** [comment]
Any comments on RESET?

**Comment by TomTheBear** [comment]
No comments, so I close the issue. I know from other users that they are quite happy with `LIKWID_MARKER_RESET`.
