### ISSUE TITLE
Marker API - MSR Read Operation failed Error that Disappears if Verbose Output is Used

### ISSUE THREAD

**Issue by mattingram0** [RRZE-HPC/likwid#189]
Hello,

I'm trying to use the lickwid-perfctr marker API to analyse a piece of matrix multiplication code. 
I am running lickwid/4.1 on a HPC cluster (that makes use of Slurm workload manager). The actual node on which the code gets run on is a:

CPU name:	Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
CPU type:	Intel Xeon Broadwell EN/EP/EX processor
CPU clock:	2.20 GHz

I have four files: *basic-sparsemm.c*, *optimised-sparsemm.c*, *sparsemm.c* and *utils.h*. *sparsemm.c* is my main file, and this calls *optimised.c* which at the moment just calls *basic.c*, in which the instrumented code lies. The instrumented code can be found [here](https://gist.github.com/mattingram0/5fb6cc2eb317b640f05f345237ee61da)

I compile and link my code with the following 4 commands:
**gcc -O3 -c optimised-sparsemm.c -o optimised-sparsemm.o** 

**gcc -O3 -c utils.c -o utils.o**

**gcc -O3 -pthread -DLIKWID_PERFMON -I/ddn/apps/Cluster-Apps/likwid/4.1/include -L/ddn/apps/Cluster-Apps/likwid/4.1/lib basic-sparsemm.c -o basic-sparsemm.o -c**

**gcc -O3 -pthread -DLIKWID_PERFMON -I/ddn/apps/Cluster-Apps/likwid/4.1/include -L/ddn/apps/Cluster-Apps/likwid/4.1/lib -o profile sparsemm.c optimised-sparsemm.o basic-sparsemm.o utils.o -llikwid -lm**

If I then run likwid-perfctr with the following command, or with **-V 1** added,
**likwid-perfctr -f -C 0 -g DATA -m ./profile CHECK**
then I get the following error ('CHECK' above is just a command line argument for my program):

```
--------------------------------------------------------------------------------
No event in given event string can be configured
ERROR - [./src/includes/perfmon_broadwell.h:1567] MSR read operation failed - Bad file descriptor 
ERROR - [./src/includes/perfmon_broadwell.h:1567] MSR read operation failed - Bad file descriptor 
No event in given event string can be configured
--------------------------------------------------------------------------------
ERROR - [./src/perfmon.c:perfmon_getMetricOfRegionThread:2592] Interrupted system call.
Cannot calculate formula FIXC1/FIXC0
ERROR - [./src/perfmon.c:perfmon_getMetricOfRegionThread:2592] Interrupted system call.
Cannot calculate formula PMC0/PMC1
```

but if I run with **-V 2** or **-V 3** the error doesn't occur, and performance data is outputted as expected. Any help on the matter would be massively appreciated, sorry for the long post!

The full error logs can be found here:
- [Non verbose](https://gist.github.com/mattingram0/86eb80c7f92122aa899b49d26f8e7298)
- [With -V 1](https://gist.github.com/mattingram0/50aead99d91fa750879d5daf6e88cc5b)
- [With -V 2](https://gist.github.com/mattingram0/686e7ce81e11c7afae2fc2b14c43bdaf)
- [With -V 3](https://gist.github.com/mattingram0/64e3aa2e10ce621d753a886a46e1dcdd)

**Comment by TomTheBear** [comment]
In 4.1.x it is not possible to run MARKER_INIT and MARKER_CLOSE multiple times, it will always reset the library including strange behavior and you probably call the dgemm code multiple times. A fix for MARKER_INIT was added in 4.3.x. Generally, it is a bad idea to call MARKER_CLOSE multiple times, because it creates the output file and overwrites the file in all subsequent calls.
Why you don't get output with verbosity levels 0 and 1 is unclear but 4.1 is pretty old (> 2 years) and it would cause a lot of work to reproduce your error.

Try to restructure your code to call MARKER_INIT, MARKER_THREADINIT and MARKER_CLOSE only once. Moreover, to reduce possible sources of error, compile in a single call:
`gcc -O3 -pthread -DLIKWID_PERFMON -I/ddn/apps/Cluster-Apps/likwid/4.1/include -L/ddn/apps/Cluster-Apps/likwid/4.1/lib -o profile sparsemm.c optimised-sparsemm.c basic-sparsemm.c utils.c -llikwid -lm`

I'm not sure whether it works, but maybe you can use the 4.3.x version with the 4.1.x accessDaemon. Download/Clone 4.3.2, edit PREFIX in config.mk to point to /ddn/apps/Cluster-Apps/likwid/4.1 , run make and make local. It output a command like `export LD_LIBRARY_PATH=....`. Copy and execute the command . Afterwards try to call `./likwid-perfctr ...` and link with the home-installed library.

**Comment by mattingram0** [comment]
Thanks a lot for the quick reply, I'll try all of that, and pester our system admins to update to 4.3.x.

**Comment by TomTheBear** [comment]
Any novelties in this issue? Did it work with 4.3? If everything is fine, can we close this issue?

**Comment by mattingram0** [comment]
No novelties in the issue - using your work around I was able to get it working. Never tried it on 4.3 I don't think, but yeah feel free to close the issue.
