### ISSUE TITLE
Implement per thread first-touch policy in likwid-bench

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/likwid#210]
`likwid-bench` allocates and initializes data on first thread, not on the threads which will eventually use it. This leads to performance issues if the thread group in a domain spans multiple NUMA domains.

It should be sufficient to move initialization with the threads for better performance and more intuitive behaviour.

**Comment by moebiusband73** [comment]
When I implemented it the default is that the first thread in the thread group (workgroup) initialises the data. You may also freely specify where to place a stream. I do not understand the issue. I think you can realize any setting you want with the options as is. If a thread group spans multiple memory domains then you may want to use the thread group that maps on the memory domains (M) and use multiple of those.

Please Thomas correct me if I am wrong.

But you either can use multiple work groups, one for each  memory domain (M prefix) in addition you can freely place the streams on any topological entity for every work group separately.

I am not sure if relocating the thread initialisation breaks the data placement options. It was not intended to be used that way as described above.

**Comment by cod3monk** [comment]
Currently it is not possible to achieve this:
Skylake with 20 cores and SNC enabled (cores 0-9 and 10-19 in S0 are on separate NUMA domains).
I would like to use the load benchmark on cores 0-14 in S0 with optimal data placement.

Options are:
* `-w S0:1GB:15` places the date at core 0, which means that cores 10-14 are using off-NUMA-domain accesses.
* `-w M0:666MB:10 -w M1:333MB:5` is not allowed because each thread group needs to have the same number of threads.
* `-w S0:1GB:15-$something` only allows placement of streams not of parts of streams. My only option here is to place stream 0 completely onto M0 or M1.

Ideally one would be able to place each stream's thread-local section onto any NUMA domain individually, but first-touch on a thread-by-thread basis is probably what most users typically want in most scenarios.

**Comment by TomTheBear** [comment]
@moebiusband73 : You described it correctly.

Yes it breaks the data placement options, see my comments in the PR: https://github.com/RRZE-HPC/likwid/pull/212
There is probably a way to achieve both, allocation in specified domain(s) and thread-by-thread initialization but it will be more complex than just moving the initialization into `runTest()`.

**Comment by moebiusband73** [comment]
Hi Julian,

the basic principles likwid-bench is build on is explicit and transparent behaviour.
And the statement "is probably what most users typically want " kind of violates this :-).

I understand your problem better now and the issue is actually not related to data placement but to the fact that thread groups currently can not have differing thread counts. This is a microbenchmark and its behaviour should not depend on some implicit hardware feature.

I guess you are aware that performance wise this does not make much sense as the threads in the NUMA domain with less threads see  more bandwidth and therefore introduce a load imbalance among threads. But if this is what you want to see than thats fine.

The pthread wrapper module is able to handle differing number of threads for different work groups. So technically it should be possible to do that but I am not sure if it is probably required to introduce new data structures. I have to discuss with Thomas.

**Comment by cod3monk** [comment]
I do not see how `-w S0:1GB:15` transparently informs me that the data will be initialized on core 0 out of the S0 domain. Why not the last core?

Wouldn't it make sense to completely untangle thread and data placement on a thread-by-thread basis? That would allow full control over what happens and–if required to be provided–make it very transparent.

Allowing to run with uneven number of threads would be–in my opinion–be a workaround for my problem, but none the less solve it.

**Comment by moebiusband73** [comment]
Hi Julian,
the concept is that per default the data gets placed in the same topology domain as specified in the work group, and this is exactly what happens. As you note one could use any processor in the topology domain, but one processor is enough to place the data. This happens in a transparent way as likwid-bench outputs which processor is used for each Stream. The fact that it is relevant for you that on your machine there are two memory domains inside a socket indicates that you should and have to use the memory topology domains, thats the part about explicit.

I do not see what is unclear or wrong with this behaviour. Everything else would make things unnecessarily complicated.

**Comment by TomTheBear** [comment]
I support the idea to have different numbers of threads in the workgroups but not the per-thread initialization because if we want to make this transparent we would have to write for each stream chunk which thread (CPU core) was used for initialization. The number of threads are specified by the user, so totally transparent and I would output a warning if the thread counts do not match, just to draw the users' attention to the fact that it is not optimal.

**Comment by moebiusband73** [comment]
We discussed today and a compromise could be to not change the default behaviour  but introduce an additional flag for per thread initialization. This flag would enable then first touch initialisaten with all threads.

**Comment by TomTheBear** [comment]
Sounds ok. And how to handle explicit placement of streams with the option? Either per thread initialization or placement of streams? Or should the combination be possible?
