### ISSUE TITLE
confused about Marker API with C/C++ some function

### ISSUE THREAD

**Issue by gengtsh** [RRZE-HPC/likwid#211]
hi,

i feel confused about 3 functions in C-markerAPI.c (MarkerCtutorial)
1. LIKWID_MARKER_REGISTER("example"),
2. LIKWID_MARKER_START("example");
3. LIKWID_MARKER_STOP("example");

these three functions are called in three places: line 55, 67,72
since all these three function are called in #pragma omp parallel, so every thread will create a LIKWID_MARKER_START tagged with "example" and LIKWID_MARKER_STOP tagged with "example";
my question is : are the regions thread private? 

it's the same problem about pthread :
i used pthread_create to create several threads, every thread creates a LIKWID_MARKER_START tagged with "example" and LIKWID_MARKER_STOP tagged with "example", and the region were stopped by call LIKWID_MARKER_STOP("example") when the threads were destroyed.
the demo is: 
Thread Thread_Local[3];
for (int i=0; i< 3; ++i)
{
      Thread_Local[i].run();
} 
Thread::run()
{
    pthread_create(&thread_,&attr,function_,argument_);
    LIKWID_MARKER_THREAINIT;
    LIKWID_MARKER_REGISTER("emample");
    LIKWID_MARKER_START("example");_
}
Thread::~Thread()
{ 
   LIKWID_MARKER_STOP("example");
   pthread_attr_destrop(&attr);
}
i got two types of **warning**: 

WARN: Region schedule was already started
WARN: Stopping an unknown/not-started region schedule

are these two **warnings** really matter? 

I really appreciated if you clear my confusion, thanks in advance.

**Comment by TomTheBear** [comment]
The threads are differentiated by the CPU they are running on. That's why MarkerAPI works only if you pin the threads to CPUs (-C on the command line or self-pinning before the first REGISTER() or START() call)

Each thread has a unique ID given by the pthread library (see `pthread_self()`). The pthread lib is the core of almost all parallel environments (OpenMP, Cilk+, ...). But the MarkerAPI is not using this ID.

Your C++ code contains some errors (example vs. emample, ;_ at line ends, pthread_attr_destrop). Not sure whether your code is really like that or it's a copy&paste problem. For example, there is no region 'schedule' in your code but the warnings mention it. And, of course, warnings matter. Otherwise LIKWID wouldn't print them.
The C++ code is doing it wrong, that's why you get the warnings. Your run() function creates a thread but you don't execute the LIKWID calls in the thread but in the main process. The LIKWID calls should be in the `function_` you are handing over to pthread_create.

**Comment by gengtsh** [comment]
thanks TomTheBear,
thanks for point out my mistakes and typo, i also noticed that my c++ pthread demo has some issues since i execute likwid in the main process.

here, thread is pinned on the CPU. 
Based on your first paragraphs, if i'm not understanding wrong, every thread can create/start a region call "example" , and stop region "example". Likwid will separately collect performance counter in different threads' "example" region.  likwid will create a hash table for each thread, so likwid don't care whether different threads has same region name or not. 

please correct me if i'm wrong, thanks in advance.

**Comment by TomTheBear** [comment]
You are right, each thread/CPU has a hash table and each table can contain differently named regions. The output of likwid-perfctr is, of course, different as well, if each thread uses a different name. The results are not in a few tables (2 or 4) but you get 2 or 4 tables for each region name and each with one column for the CPU.

**Comment by gengtsh** [comment]
thanks TomTheBear, 
if i want to have only one table at the end, i should use the same region name in all threads, am i correct?
so, in this case, at the end likwid will check the region name of every thread and combine the threads with same region name together to form a table, am i correct?

but i encounter the similar problem when i use the same region name "example":
please see the following pseudo code:
int main(){
      for (int i=0;i<5;++i){
           pthread_create(&thread_[i],&attr,function_,argument_);
      }
      ....
      for(int j=0;j<5;j++){
           thread_join(thread_[i],null);
      }
  
}
static void *function_(void *arg){
    LIKWID_MARKER_THREAINIT;
    LIKWID_MARKER_REGISTER("emample");
    LIKWID_MARKER_START("example");_

    for (int i=0;i<100;i++){
         for(int j=0;j<i;++j){
         
         }
    }
    LIKWID_MARKER_STOP("example");
}

i get the same warning that 
WARN: Region example was already started
WARN: Stopping an unknown/not-started region example

i don't know what's happen, it should work since the function_ will be called by different threads.

i really appreciate if you can point what wrong with my understanding or my pseudo code demo

**Comment by TomTheBear** [comment]
Correct, it collects all equally named regions of all threads and combines them to a single region output.

First, please attach working code! I don't want to point to the errors this time, just the LIKWID-related:
There is no `LIKWID_MARKER_INIT` and `LIKWID_MARKER_CLOSE` in the serial part (`main()`). Moreover, `LIKWID_MARKER_THREAINIT` (even if typed correctly) is not required anymore (in most cases, it's only required for parallel environments that are **not** based on pthread).
Since you start 5 threads and the MarkerAPI requires them to run on different hardware threads, you have to specify at least 5 hardware threads at `likwid-perfctr`: `likwid-perfctr -C 0,1,2,3,4 -m -g <events/group> ./a.out` . If you choose less threads, multiple threads will run on the same CPU (round-robin placement of the threads in the set of specified CPUs) and you get the 'Region already started' because they do. The "Stopping and unknown region" is a hint that your region strings don't match. Your pasted code has the same region strings in start/stop but not in register, so your executed code is not the pasted one because you can register whatever region you want, the start/stop pair is the only one that matters because `LIKWID_MARKER_REGISTER` is an optional call.
Your small test loop might be optimized away by the compiler because it doesn't do anything. Even if you initialize an array, you should use the array at least once afterwards so that the compiler recognizes that this loop has to be executed (e.g. print the last element, ...).

**Comment by gengtsh** [comment]
hello TomThebear,

thank you so much. with your help, i finally find my mistakes, one is my typos and another mismatch of allocated thread number and pinned thread number. i start 5 threads, but in the likwid-perfctr command, i only pin 4 threads, that's why i got "Region already started". 

thank you so much for you help. i really appreciated.

**Comment by TomTheBear** [comment]
Congrats. Your are welcome. Can I close the issue or do you think you have further questions? You can also close it yourself.

**Comment by gengtsh** [comment]
ok, up to now, i have no further questions, i will close it. thanks again.
