### ISSUE TITLE
version and git commit hardcoded

### ISSUE THREAD

**Issue by robertschade** [RRZE-HPC/likwid#226]
Hi,
is the commit version 233ab943543480cd46058b34616c174198ba0459 hardcoded or is just the mechanism to change it broken on my system?
If there is no mechanism to read the commit hash from the git repository I would be happy to implement one.

**Comment by TomTheBear** [comment]
I added this a while ago but didn't exactly know how it would behave in the future. The commit hash is read from Github but it is only updated when the file (make/config_git.mk) is updated as well. This has never happen since the original integration (why should I but I should do it before a release....forgot it all the time). If you have ideas how to get it in a working state (without personal interaction), I would welcome your patch/PR/whatever.

**Comment by robertschade** [comment]
Why not check if likwid is being built in a directory that is a git working copy and read the commit hash from the repo?
This could be done by the make file.
If yes, I would build it.

**Comment by TomTheBear** [comment]
If that's working, feel free. You can add it in the make/config_git.mk file. The file is sourced by the main Makefile.

**Comment by TomTheBear** [comment]
Any novelties on this issue? It would be great to have this fixed until the next release (mid November)
