### ISSUE TITLE
Likwid segmentation fault when using GNU Gold Linker

### ISSUE THREAD

**Issue by jdeters** [RRZE-HPC/likwid#231]
I would like to use Likwid with a project that requires link time optimization and thus the GNU Gold Linker. When I compile with -flto using clang and link with -flto -fuse-ld=gold Likwid will segfault, if I remove -fuse-ld=gold then Likwid runs just fine.

It seems that Likwid is segfaulting in access_client.c in access_client_startDaemon() where Likwid calls the socket() system call.

```c
EXIT_IF_ERROR(socket_fd = socket(AF_LOCAL, SOCK_STREAM, 0), socket() failed);
```

I have yet to find a bug like this reported anywhere and any insight into solving this would be greatly appreciated.

**Comment by TomTheBear** [comment]
I have never done anything with link time optimization but just for my understanding:
- Your project uses lto but you compiled LIKWID like normal but at the link time optimization step, the compiler introduces a segfault in LIKWID?
- You compile LIKWID and your project with lto so that the compiler can optimize both at link time and this introduces an error?

Have you tried the non-related solutions? Like `-Wl,--no-as-needed`?

Since you have boiled it down to the single line, can you check with `gdb` whether variables are valid? The `EXIT_IF_ERROR` macro is defined in `src/includes/error.h`. The code expands to:
```
if ((socket_fd = socket(AF_LOCAL, SOCK_STREAM, 0)) < 0) {
    fprintf(stderr,"ERROR - [%s:%d] socket() failed - %s \n", __FILE__, __LINE__, strerror(errno));
    exit(EXIT_FAILURE);
}
```
Maybe the compiler/linker doesn't like these `if ((var = func()) < 0)` constructs?

**Comment by jdeters** [comment]
It doesn't seem like it's an issue with the gdb variables as I still get a segfault if I call the function directly in access_client.c. Adding `-Wl, --no-as-needed` didn't resolve the issue either. 

Valgrind reports `Bad permissions for mapped region at address 0x415880`. I'm not really sure why the GNU gold would have this issue, but GNU ld would not.

**Comment by TomTheBear** [comment]
Was Valgrind also able to name what this memory region is? The address looks quite low ... uncommon for user-level allocated space, so it might be some mapped system library.

You havn't answers my questions from the last post. Or let's pose it differently: Is it crucial to compile LIKWID with GNU gold?

**Comment by jdeters** [comment]
It is crucial that I link with GNU gold in my final executable. I'm writing a performance monitoring tool that needs LTO. 

I'm going to close this issue as I believe that this is coming from outside Likwid itself and I will just attempt to find a work around. Thanks for the help.
