### ISSUE TITLE
Reading CAS_COUNT_* on broadwell-EP

### ISSUE THREAD

**Issue by etiandre** [RRZE-HPC/likwid#234]
Hello,

This issue looks related to #142, although I'm not sure.

The broadwell-EP MEM group file reads CAS_COUNT_RD and CAS_COUNT_WR from MBOX0C* to MBOX7C*.

Indeed, using likwid-perfctr, I can read these counters (with some values being replaced by '-', as stated in issue #142) :

`likwid-perfctr -c 0,1 -g CAS_COUNT_RD:MBOX0C0,CAS_COUNT_WR:MBOX0C1,CAS_COUNT_RD:MBOX1C0,CAS_COUNT_WR:MBOX1C1,CAS_COUNT_RD:MBOX2C0,CAS_COUNT_WR:MBOX2C1,CAS_COUNT_RD:MBOX3C0,CAS_COUNT_WR:MBOX3C1,CAS_COUNT_RD:MBOX4C0,CAS_COUNT_WR:MBOX4C1,CAS_COUNT_RD:MBOX5C0,CAS_COUNT_WR:MBOX5C1,CAS_COUNT_RD:MBOX6C0,CAS_COUNT_WR:MBOX6C1,CAS_COUNT_RD:MBOX7C0,CAS_COUNT_WR:MBOX7C1 -t 1s`

But some of these seem to be undefined. For example, executing `likwid-perfctr -c 0,1 -g CAS_COUNT_RD:MBOX0C0 -t 1s` returns :

`ERROR: No event in given event string can be configured.
       Either the events or counters do not exist for the
       current architecture. If event options are set, they might
       be invalid.`

Another maybe related problem is reading those counters from the likwid API. I'm using pylikwid (code can be found at https://github.com/etiandre/uncore-regulator/blob/master/uncore_regulator/daemon.py ), and reading from those "undefined" counters is allowed, but randomly gives very strange results. Maybe I can make that into it's own issue.

For reference, the CPU used is an Intel(R) Xeon(R) CPU E5-2680 v4. Am I missing something ?

**Comment by TomTheBear** [comment]
Is MBOX0C0 one of the counter registers that returns a dash or 0? If yes, this memory channel is not available on your machine. You can get this information by running with `-V 1`. I moved it to verbosity level 1 because if you use the MEM group, LIKWID would print out multiple lines of "Device or register does not exist". Users were annoyed by this output.
You should run and parse likwid-perfctr -e first (probably you can also use the python function to get counters and events) because this list contains only the counters that are available on your machine (does the same checks as addEventSet). With this info you can create a tailored eventset for your machine.
The counters should never return randomly very strange results. So, if this is really the case, please open a separate issue for that.
I admit, the "dash printing" is not perfect and I'm not sure why. Some systems pass the checks but the counter registers always return 0. In this case, LIKWID cannot decide whether the "Device/Counter is not available" or it is working but the programmed event never happened.

**Comment by TomTheBear** [comment]
Just for info, the branch `persistent-freq-daemon` is faster when setting CPU frequencies. And it would be great if someone else would test it so I can merge it soon.

**Comment by TomTheBear** [comment]
The `persistent-freq-daemon` PR was merged in the master.

Can I close this issue or do you have follow-up questions?
