### ISSUE TITLE
Memory bandwidth mismatch between likwid-bench and likwid perfctr

### ISSUE THREAD

**Issue by mknambiar** [RRZE-HPC/likwid#262]
Hi,

I ran a single threaded likwid-bench and measured the memory bandwidth using likwid-perfctr. But I am seeing different results.

To summarize
likwid-bench reports "MByte/s:                29052.78"
likwid-perfctr reports "|    Memory bandwidth [MBytes/s]    | 3.349518e+15 |"

If the units are to be believed - that is a big difference.

Please help.

Regards,
Manoj

Pasting the command I ran and the output -
likwid-perfctr -g MEM -f -m likwid-bench -t stream -w S1:20MB:1
--------------------------------------------------------------------------------
CPU name:       Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
CPU type:       Intel Xeon Broadwell EN/EP/EX processor
CPU clock:      2.60 GHz
Warning: The Marker API requires the application to run on the selected CPUs.
Warning: likwid-perfctr pins the application only when using the -C command line option.
Warning: LIKWID assumes that the application does it before the first instrumented code region is started.
Warning: You can use the string in the environment variable LIKWID_THREADS to pin you application to
Warning: to the CPUs specified after the -c command line option.
--------------------------------------------------------------------------------
Warning: Sanitizing vector length to a multiple of the loop stride 4 and thread count 1 from 833333 elements (6666664 bytes) to 833332 elements (6666656 bytes)
Allocate: Process running on core 14 (Domain S1) - Vector length 833332/6666656 Offset 0 Alignment 512
Allocate: Process running on core 14 (Domain S1) - Vector length 833332/6666656 Offset 0 Alignment 512
Allocate: Process running on core 14 (Domain S1) - Vector length 833332/6666656 Offset 0 Alignment 512
--------------------------------------------------------------------------------
LIKWID MICRO BENCHMARK
Test: stream
--------------------------------------------------------------------------------
Using 1 work groups
Using 1 threads
--------------------------------------------------------------------------------
Using Likwid Marker API
--------------------------------------------------------------------------------
Group: 0 Thread 0 Global Thread 0 running on core 14 - Vector length 833332 Offset 0
--------------------------------------------------------------------------------
Cycles:                 3661355738
CPU Clock:              2596990210
Cycle Clock:            2596990210
Time:                   1.409846e+00 sec
Iterations:             2048
Iterations per thread:  2048
Inner loop executions:  208333
Size (Byte):            19999968
Size per thread:        19999968
Number of Flops:        3413327872
MFlops/s:               2421.06
Data volume (Byte):     40959934464
MByte/s:                29052.78
Cycles per update:      2.145329
Cycles per cacheline:   17.162632
Loads per update:       2
Stores per update:      1
Load bytes per element: 16
Store bytes per elem.:  8
Load/store ratio:       2.00
Instructions:           8106653713
UOPs:                   11093315584
--------------------------------------------------------------------------------
Writing Likwid Marker API results to file /tmp/likwid_41619.txt
--------------------------------------------------------------------------------
Region bench, Group 1: MEM
+-------------------+----------+
|    Region Info    |  Core 14 |
+-------------------+----------+
| RDTSC Runtime [s] | 1.409858 |
|     call count    |        1 |
+-------------------+----------+

+-----------------------+---------+--------------+
|         Event         | Counter |    Core 14   |
+-----------------------+---------+--------------+
|   INSTR_RETIRED_ANY   |  FIXC0  |   8106721000 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  |   4612051000 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  |   3444595000 |
|      CAS_COUNT_RD     | MBOX0C0 |       -      |
|      CAS_COUNT_WR     | MBOX0C1 |       -      |
|      CAS_COUNT_RD     | MBOX1C0 |       -      |
|      CAS_COUNT_WR     | MBOX1C1 |       -      |
|      CAS_COUNT_RD     | MBOX2C0 |       114568 |
|      CAS_COUNT_WR     | MBOX2C1 |        64891 |
|      CAS_COUNT_RD     | MBOX3C0 |       279992 |
|      CAS_COUNT_WR     | MBOX3C1 |       243258 |
|      CAS_COUNT_RD     | MBOX4C0 | 1.844666e+19 |
|      CAS_COUNT_WR     | MBOX4C1 | 1.844666e+19 |
|      CAS_COUNT_RD     | MBOX5C0 | 1.844666e+19 |
|      CAS_COUNT_WR     | MBOX5C1 | 1.844666e+19 |
|      CAS_COUNT_RD     | MBOX6C0 |       100213 |
|      CAS_COUNT_WR     | MBOX6C1 |        59121 |
|      CAS_COUNT_RD     | MBOX7C0 |       288064 |
|      CAS_COUNT_WR     | MBOX7C1 |       238373 |
+-----------------------+---------+--------------+

+-----------------------------------+--------------+
|               Metric              |    Core 14   |
+-----------------------------------+--------------+
|        Runtime (RDTSC) [s]        |       1.4099 |
|        Runtime unhalted [s]       |       1.7759 |
|            Clock [MHz]            |    3477.1646 |
|                CPI                |       0.5689 |
|  Memory read bandwidth [MBytes/s] | 1.674759e+15 |
|  Memory read data volume [GBytes] |      nil     |
| Memory write bandwidth [MBytes/s] | 1.674759e+15 |
| Memory write data volume [GBytes] |      nil     |
|    Memory bandwidth [MBytes/s]    | 3.349518e+15 |
|    Memory data volume [GBytes]    | 4.722345e+12 |
+-----------------------------------+--------------+

**Comment by TomTheBear** [comment]
You cannot trust these numbers, they are way to high. Try again with telling likwid-perfctr which CPU to measure.
`likwid-perfctr -g MEM -f -m -C S1:0 likwid-bench -t stream -w S1:20MB`
If you use `likwid-perfctr -V 1 ...` you get probably more output about the counter usage.

If this does not help, you might have encountered an issue I had as well on some Broadwell EP systems:
The memory channel units are exposed through PCI devices. The E5-2690 v4 has 4 memory channels, but your system provides the PCI devices for 6 channels. LIKWID checks for the PCI devices and consequently detects 6 channels (`MBOX2-7`). The detection does not only check the existence of the PCI device (path + device ID) but also the accessibility (ro, rw, ...) of the required registers. All checks are passed by the 6 devices.
In my cases the "faulty" memory channel devices returned zero, so no big issue, but your system somehow returns a high number (`1.88e+19`). You can remove the "faulty" counters (`MBOX4C0`, `MBOX4C1`, `MBOX5C0`, `MBOX5C1`) from the MEM group (including the metric formulas) to fix this.

Just as remark after the fix: The values of `likwid-bench` and `likwid-perfctr -g MEM` won't return the same memory bandwidth in most cases because `likwid-bench` does _not_ include "cache management traffic" (write allocates, RFO) while `likwid-perfctr -g MEM` includes it.

**Comment by mknambiar** [comment]
Thanks for reverting, TomTheBear.

You are probably suggesting that I ignore the faulty counters. That way the 

I am not sure if likwid-perfctr offers a way to remove them. 

Few questions

1. You are saying that (MBOX4C0, MBOX4C1, MBOX5C0, MBOX5C1)  come from PCIE devices. Is there a way for me to double check?
2. How do I correlate MBOX2C0, MBOX2C1, MBOX3C0, MBOX3C1 with the memory bandwidth provided by likwid-bench. Numbers look similar, but I am not sure about the units reported by the MBOX counters
3. Is there a way to disable write-allocates on my system. (Sorry for being too naïve)

Regards,
Manoj

**Comment by TomTheBear** [comment]
Hi Manoj,

the performance groups are simple text files (see https://github.com/RRZE-HPC/likwid/blob/master/groups/broadwellEP/MEM.txt), so if you remove the counters MBOX4C0, MBOX4C1, MBOX5C0, MBOX5C1 in that file in your installation, you can use the MEM group afterwards for reliable measurements. Or you copy and adapt the file and put it in your home directory (`$HOME/.likwid/groups/broadwellEP/`) with a different name like `MEMORY.txt`. Afterwards, you can run `likwid-perfctr -g MEMORY ...`

The raw values for counters MBOX*C0 report the read memory lines from the memory channel, the counters MBOX*C1 measure the written memory lines. So, in order to get the data volume, sum up the values and multiply by 64 (one memory line on x86 CPUs is 64 Byte, same as cache lines).

You cannot disable write-allocates, they are required by the cache coherency protocol. But you can force the usage of non-temporal stores which do not require write-allocates (they bypass the caches, so no cache coherency required). In `likwid-bench` the kernels containing `_mem_` are using these instructions. The benefit is also that the numbers of `likwid-bench` and `likwid-perfctr -g MEMORY` match.

**Comment by mknambiar** [comment]
ok - Thanks for reverting TomTheBear
