### ISSUE TITLE
likwid power-meter does not show output

### ISSUE THREAD

**Issue by mahmood83** [RRZE-HPC/likwid#263]
I install likwid on ubuntu but when use likwid-powermeter nothing show as output. I see only zero for energy and power.
![output](https://user-images.githubusercontent.com/31089189/72097806-6a1eb480-3332-11ea-94ad-16a9658df23e.PNG)

**Comment by mahmood83** [comment]
I installed the tools on ubuntu as a host OS on another physical machine and the problem resolved.

**Comment by TomTheBear** [comment]
As I wrote you in the personal email, LIKWID is not thought for running inside virtual machines. There might be combinations of Host OS, Guest OS and virtualization software that might work for core-local performance measurements because they can be counted for a single process (using perf_event) but all socket-related counters (energy, memory controllers, ...) will never work.
