### ISSUE TITLE
 Validate Phi events

### ISSUE THREAD

**Issue by rrze-likwid** [RRZE-HPC/likwid#3]
sursri wrote:
I was surprised to see L2_DATA_READ_MISS_MEM_FILL, L2_DATA_READ_MISS_CACHE_FILL as 0 for few programs when measured in PMC1, so i made a comparison with VTUNE and feel that there is some problem with likwid-perfcntr?

Later when I ran experiment running only 1 event with PMC0 i got some small values.  I dont see any document mentioning that it can be measured only with PMC0. And there is a huge difference in L2_DATA_WRITE_MISS_MEM_FILL, L2_DATA_READ_MISS_CACHE_FILL compared to VTUNE. Can you help me with this?

What steps will reproduce the problem?
1. I ran an array copying program using both VTUNE and likwid.

What is the expected output? What do you see instead?

	                           | likwid	     |      Vtune
---------------------------|--------------|-----------------
DATA_READ	   |        200292452 | 216400000
DATA_WRITE	   |      130125076	| 380400000
BANK_CONFLICTS	   |       5197	| 100000
BRANCHES	|        110225835	| 123100000
INSTRUCTIONS_EXECUTED |  1291182962	| 1370940000
DATA_READ_OR_WRITE	|330451293	| 609500000
DATA_READ_MISS_OR_WRITE_MISS	| 42962603	|     74130000
L2_DATA_READ_MISS_CACHE_FILL |	4389	    |       120000
L2_DATA_WRITE_MISS_CACHE_FILL	| 129949990	| 129870000
L2_DATA_READ_MISS_MEM_FILL	| 200038669	| 199920000
L2_DATA_WRITE_MISS_MEM_FILL	| 3876	     |  30140000

What version of the product are you using?
likwid-perfctr  3.0 

Please provide any additional information below.
I ran if for add program of stream benchmark with just 1 thread. 

jan.eitzinger@fau.de:
> Hi, the event ID and umask I use for these events are according to the documentation. In the 
> documentation it says that FUB is CRI :-). No idea what this means, they do not introduce those 
> terms. The only way to say who is right is to compare against a microbenchmark where you know 
> the result. I plan to do this for Phi also.  I find it suspicious that the vtune results are all flat to the
> fifth digit. Are those end to end measurements?

sursri:
> I am running the same program pinned on different core on xeon phi and 
> measuring the same event. and the values are different in different 
> cores. please checkout the result of multiple runs.
> 
> ```
~/perf_anal $ /home/snataraj/perf_anal/likwid/likwid-perfctr -g 
L2_READ_HIT_M:PMC0 -C 58 -O  /home/snataraj/perf_anal/copy
-------------------------------------------------------------
-------------------------------------------------------------
CPU type:       Intel Xeon Phi Coprocessor
CPU clock:      1.05 GHz
-------------------------------------------------------------
/home/snataraj/perf_anal/copy
K=1048577
Status: 0x0
Event,core 58
L2_READ_HIT_M,10761.000000
```
> ```
~/perf_anal $ /home/snataraj/perf_anal/likwid/likwid-perfctr -g 
L2_READ_HIT_M:PMC0 -C 58 -O  /home/snataraj/perf_anal/copy
-------------------------------------------------------------
-------------------------------------------------------------
CPU type:       Intel Xeon Phi Coprocessor
CPU clock:      1.05 GHz
-------------------------------------------------------------
/home/snataraj/perf_anal/copy
K=1048577
Status: 0x0
Event,core 58
L2_READ_HIT_M,11010.000000
```
> ```
~/perf_anal $ ./work_1.sh
~/perf_anal $ /home/snataraj/perf_anal/likwid/likwid-perfctr -g 
L2_READ_HIT_M:PMC0 -C 40 -O  /home/snataraj/perf_anal/copy
-------------------------------------------------------------
-------------------------------------------------------------
CPU type:       Intel Xeon Phi Coprocessor
CPU clock:      1.05 GHz
-------------------------------------------------------------
/home/snataraj/perf_anal/copy
K=1048577
Status: 0x0
Event,core 40
L2_READ_HIT_M,0.000000
```
> ```
~/perf_anal $ /home/snataraj/perf_anal/likwid/likwid-perfctr -g 
L2_READ_HIT_M:PMC0 -C 10 -O  /home/snataraj/perf_anal/copy
-------------------------------------------------------------
-------------------------------------------------------------
CPU type:       Intel Xeon Phi Coprocessor
CPU clock:      1.05 GHz
-------------------------------------------------------------
/home/snataraj/perf_anal/copy
K=1048577
Status: 0x0
Event,core 10
L2_READ_HIT_M,10768.000000
```
> ```
~/perf_anal $ /home/snataraj/perf_anal/likwid/likwid-perfctr -g 
L2_READ_HIT_M:PMC0 -C 40 -O  /home/snataraj/perf_anal/copy
-------------------------------------------------------------
-------------------------------------------------------------
CPU type:       Intel Xeon Phi Coprocessor
CPU clock:      1.05 GHz
-------------------------------------------------------------
/home/snataraj/perf_anal/copy
K=1048577
Status: 0x0
Event,core 40
L2_READ_HIT_M,0.000000
```
> ```
~/perf_anal $ /home/snataraj/perf_anal/likwid/likwid-perfctr -g 
L2_READ_HIT_M:PMC0 -C 54 -O -m /home/snataraj/perf_anal/copy
-------------------------------------------------------------
-------------------------------------------------------------
CPU type:       Intel Xeon Phi Coprocessor
CPU clock:      1.05 GHz
-------------------------------------------------------------
/home/snataraj/perf_anal/copy
K=1048577
Status: 0x0
=====================
Region: Compute
=====================
Region Info,core 54
RDTSC Runtime [s],0.021591
call count,1.000000
Event,core 54
L2_READ_HIT_M,158.000000
```
> ```
~/perf_anal $ /home/snataraj/perf_anal/likwid/likwid-perfctr -g 
L2_READ_HIT_M:PMC0 -C 4 -O  /home/snataraj/perf_anal/copy
-------------------------------------------------------------
-------------------------------------------------------------
CPU type:       Intel Xeon Phi Coprocessor
CPU clock:      1.05 GHz
-------------------------------------------------------------
/home/snataraj/perf_anal/copy
K=1048577
Status: 0x0
Event,core 4
L2_READ_HIT_M,524291.000000
```
sursri:
> Reply from intel forum:
> 
> FUB must stand for something like "Functional Unit Block" because P54C 
> refers to the processor core (P54C is a specific version of the Pentium 
> core, though the actual core in the Xeon Phi has been heavily upgraded 
> from the original P54C), CRI refers to the "Cache-Ring-Interface", and 
> VPU refers to the "Vector-Processing-Unit". In the Xeon Phi performance 
> counters, the UMASK field actually specifies the functional unit for 
> which the event is requested, with 0x00 referring to the core (P54C), 
> 0x10 referring to the CRI, and 0x20 referring to the VPU. This was 
> confusing to me at first because because on other processors the UMASK 
> is almost always used to modify the specific details of what is measured 
> by an Event Select code, rather than actually specifying the Unit on 
> which the measurements should occur.   On Xeon Phi the UMASK field is 
> used in a way that is much closer to what you would expect a "Unit Mask" 
> to mean -- it specifies the "Unit" for which you want the measurements 
> to be taken.

**Comment by TomTheBear** [comment]
Hi sursri.

At first I hope you have found your way to the new GitHub page.

Today I checked the accuracy of LIKWID's counters for Intel Xeon Phi, especially the memory bandwidth related counters.
At first, I cannot reproduce the problem that the counts for the same events on different core show big differences. I tested about 60 hardware threads and all show similar results.

Now to the other points. It is hard to perform the same operation as you did because I don't have your test program. I used the likwid-bench and later the 'add' part of the STREAM benchmark with the Marker API.
- I attached some pictures that show the quality of the counters we have chosen for the Xeon Phi. The only thing I can test with likwid-bench for comparison is the memory bandwidth. I have chosen the events DATA_READ_MISS_OR_WRITE_MISS and DATA_CACHE_LINES_WRITTEN_BACK to hopefully cover the complete memory traffic.
I selected the array sizes 128kB, 2MB and 1GB and each size is tested 10 times. So the first 10 points are for 128kB, second 10 points for 2MB and so on. The used microbenchmarks are copy (`A[i] = B[i]`), triad (`A[i] = B[i] + c * C[i]`), load (`A[i] = c`) and store (`reg = A[i]`) where `c` is some constant and `reg` is one of the CPU's register. Tests are run on a single hardware thread and are written in assembly without any prefetch instructions.
The measurements of all benchmarks except store show a high accuracy:
![copy](https://cloud.githubusercontent.com/assets/2751628/8109267/06185e7c-1056-11e5-8a59-6b432af7a70e.png)
![triad](https://cloud.githubusercontent.com/assets/2751628/8109844/48edd09e-1059-11e5-9a99-ee80c92dd1c9.png)
![load](https://cloud.githubusercontent.com/assets/2751628/8125857/b993a7b6-10e9-11e5-9a5b-fa536f0023ed.png)
![store](https://cloud.githubusercontent.com/assets/2751628/8125970/d4215a46-10ea-11e5-997f-ffd2d03c2687.png)
The 'bench w RFO' is a scaled up version of 'bench' in the store plot. I did this because likwid-bench does not take the Read-For-Ownerships/write allocates into account. Although we are only storing data, the system previously needs to load the cache line to L1. The event DATA_READ_MISS_OR_WRITE_MISS increments for the store miss but the internally triggered load is not counted directly. The internal load is counted as write miss and the actual write should be counted by the DATA_CACHE_LINES_WRITTEN_BACK event. I omitted the original values of bench of triad and copy because the RFO is the one that reflects the true traffic.
Moreover, the event DATA_READ_MISS_OR_WRITE_MISS counts only demand reads and writes that miss the internal cache, prefetched cache lines are not counted. As soon as I add prefetches to the assembly, the memory bandwidth cannot be measured accurately anymore.
I run again the store benchmark but this time with different events: L2_VICTIM_REQ_WITH_DATA and SNP_HITM_L2. Since we execute on a single HW thread, there are no snoops to other cores' caches, hence event  SNP_HITM_L2 is zero. These two events are recommended by Intel to measure the memory write traffic, see [Optimization and Performance Tuning for Intel&reg; Xeon Phi&trade; Coprocessors, Part 2](https://software.intel.com/en-us/articles/optimization-and-performance-tuning-for-intel-xeon-phi-coprocessors-part-2-understanding):
![store_mem_write](https://cloud.githubusercontent.com/assets/2751628/8109528/8237030e-1057-11e5-8a11-a895d339aab7.png)
As soon as the array is larger than L2 cache (512kB) of the Xeon Phi, the counts are accurate. Using the event L2_VICTIM_REQ_WITH_DATA instead of DATA_CACHE_LINES_WRITTEN_BACK for the overall memory bandwidth, the counts for the store benchmark are below the reported only before we do the RFO scale, hence it's not an alternative to DATA_CACHE_LINES_WRITTEN_BACK.

- My results for the add part of the STREAM benchmark (compiled with -O3) are much different from the numbers you wrote us in the beginning. Have you measured array initialization and finalization? But nevertheless, the bandwidth reported by STREAM for "add" and the measured one does not fit.
STREAM: 3213.7695 MByte/s
LIKWID: 1525.742 MByte/s
If I reduce optimization level to -O1 (no prefetches)
STREAM: 1000.3440 MByte/s
LIKWID: 1333.876  MByte/s
Further reduce to -O0
STREAM: 339.5588 MByte/s
LIKWID: 453.2443 MByte/s

It's a not satisfying that the Xeon Phi has only two counters because we cannot combine all events to fully cover desired metrics but better than no counters at all.
I cannot compare the measurements of LIKWID with VTune because we have no VTune installed, so I cannot say anything about the error rate of LIKWID or VTune.

I hope my investigation helps you...even after the long time that this issue was deferred.

Greetings,
Thomas

**Comment by TomTheBear** [comment]
I'm going to add a page for Intel Xeon Phi to the Wiki page https://github.com/RRZE-HPC/likwid/wiki/TestAccuracy . Since nobody replied on this issue, I assume it is clear now.
