### ISSUE TITLE
[Question] Monitoring the disk activities

### ISSUE THREAD

**Issue by mcolmant** [RRZE-HPC/likwid#31]
Hello,

First of all, I would like to thank you for developing this tool, it's very helpful for my work.
I have one question regarding the hardware counters available in the Haswell EP architecture.

Are they any counters available to monitor the disk activities?
I have some insights by using several counters related to uncore or memory but is it the right way to achieve such monitoring?

Thanks for your help.

**Comment by TomTheBear** [comment]
Hi,

It's nice to read that LIKWID helps you with your work.

Disk activities cannot be monitored directly. Of course disks have counters but there are no plans to integrate them in LIKWID. At first LIKWID would require something like a plugin interface to add such features. I'm thinking about it for a long time now but there is no time to implement it.

The only thing you can do is monitoring the PCIe interface with the PBOX counters but you need of course a disk that is attached to the PCIe "bus" and you cannot differentiate between the disk and other PCIe devices.

I think the easiest way to montior disk activities are the values in /sys/block/sdX/sdX*/stat. Simply read them before and afterwards or write a small lib that aggregates the values if you want to do measurements like the Marker API. I assume there is already such a library available anywhere because you are probably not the first trying to measure the disk activity.

Greetings

**Comment by mcolmant** [comment]
Thank you for your answer. We will carefully look at these points.
