### ISSUE TITLE
Using all 8 Performance Counters When Hyperthreading is Off?

### ISSUE THREAD

**Issue by nkurz** [RRZE-HPC/likwid#32]
Intel's docs say that for Sandy Bridge onward, all 8 PMC's are available for the single active thread if hyperthreading is disabled.  See Tables 18-30, 18-42, and 18-53 all entitled "Core PMU Comparison": http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-system-programming-manual-325384.pdf

Does Likwid allow for use of more than 4 PMC's at a time?

**Comment by TomTheBear** [comment]
Currently, the lists of counters and events are statically created for each architecture at compile time. There is no extension at runtime that would be required to enable the additional counters in no HT case. Filtering is applied, so we could extend the counter list at compile time to eight counters and filter it at runtime.
But, how should the performance groups handle that. If you create a performance group with eight PMCs, how should LIKWID behave when only four PMCs are available? Measure only the first four events? Create 2 event sets and switch between them? At which rate? Scale the results of the two event sets? Are the derived metrics meaningful afterwards? Allow only up to four PMCs in Performance groups? So, many problems that need to be solved.

By now, only four PMC counters are supported.

**Comment by nkurz** [comment]
Perhaps consider the presence or absence of hyperthreading to be a  architectural variants, and choose the appropriate performance group directory at runtime by looking at the number of counters available?   Or just consider it an entirely different architecture with its own events.   The thread/core distinction no longer matters, so some things could be dropped.  A little ugly to duplicate, but straightforward, and they might diverge over time. 

Simply restricting the performance groups to 4 while allowing 8 at the command line would be fine for my purposes.     Or better (for me) not restricting to 4 for custom sets, but just sticking to 4 in the standard ones.  I'd guess that the number of people who create their own performance groups is small, and if someone is creating something for their own system, they presumably have reason to believe it will work.  As long as the error message is clear, it seems quite safe.  For that matter, even including some standard sets that use more than 4 would be safe as long as the error message is appropriate when used on a 4 counter system.  

One of the things I'd like it is for simultaneously checking execution stats for all 8 ports with UOPS_DISPATCHED_PORT_PORT_[0-7], possibly running as a system monitor in timeline mode.  Single shot full histograms of of UOPS_EXECUTED_CYCLES with CMASKS [1-8] would occasionally be useful too.  I think you are correct that you don't want to scale or switch sets, but making full use fo the available resources seems like a good design goal.

**Comment by TomTheBear** [comment]
I fully agree that supporting all available resources should be one design goal and that is helps in some situations (exec port usage statistics, ...) but currently the whole LIKWID development lies in my hands and I don't have time for "new" features.

I could choose the perf. groups directory based on the HT settings, that would be a straightforward possibility. But it also means that I have to keep care of almost twice the group files. Moreover, I have to include the PMC4-7 counters in the static counter list and if somebody prints out all counters, they are there but not usable in the HT case. There is no filtering when getting the list of all events and counters, originally because we don't have access to the registers in that function. Of course I can test for HT, but not e.g. whether a Uncore counter register is available or not.

Error message is also problematic. I had warnings when a counter is filtered out. Since the perf. groups contain all possible boxes and counters, e.g. MBOX[0-7]C[0-3], there is commonly the problem that the current machine supports only a part of them. But users were confused by the messages so I moved the warning from verbosity level 0 (default) to 1. So they see it only with -V 1.

When I have some free time, I take care of this.

**Comment by TomTheBear** [comment]
I had some time and implemented the support for the additional PMCs that are available when HyperThreading is deactivated.
Part of the implementation is, that the counter and event lists are filtered so that they contain only available counters and only events for which a counter exists. In order to limit the work, the filtering is done only explicitly when the user wants the list. For normal measurements, the counters are filtered when the event set is read in.
I only added the counters for Intel Haswell (Desktop) systems because that is my main development machine. I am going to add them to the other architectures as well but is a tedious work because all counter definitions after the PMC counters need to be adapted and unfortunately the PMC counters are at the beginning of the list. So, if you want to test it on another machine, you have to add the counters yourself.

Commit https://github.com/RRZE-HPC/likwid/commit/a506877e0696a830e9fa507843d4717bf62deda5

Moreover, I thought about how to handle performance groups for eight PMC counters and I thought about introducing some kind of condition string in the performance group files which defines when they can be used. Since the current performance groups are also valid for the nonHT case, they don't need any precondition and thus no modifications.

**Comment by nkurz** [comment]
Hi Tom --  All that sounds great.  I'll need to have someone change the BIOS on a remote machine to disable hyperthreading before I can test it properly, but after that's done I'll try it out and probably contribute a patch for the Skylake counters.   Might take me a bit of time to get to it, but thanks for improving this!

**Comment by TomTheBear** [comment]
Small help for your tests:
https://github.com/RRZE-HPC/likwid/commit/539cd7df580116917164664daa46a74957f97e48

**Comment by TomTheBear** [comment]
So, I just committed the filtering of performance groups based on a constraint string. If a performance group file contains `REQUIRE_NOHT`, it is not shown in the group list (`-a`) and cannot be set on the command line. I added an error message if someone tries:
`Performance group X only available with deactivated HyperThreading`

For Intel Haswell (Desktop) I added a group PORT_USAGE to monitor the execution ports 0-7.

**Comment by TomTheBear** [comment]
All capable architectures support all eight counters now. I created a PORT_USAGE group for each of the architectures.
What do you mean with histogram of UOPS_EXECUTED_CYCLES. There are only 4 different events for cmask 1-4. You can of course add the stall and in-use event but for the histogram 4 counters are enough.

**Comment by nkurz** [comment]
> All capable architectures support all eight counters now. I created a
> PORT_USAGE group for each of the architectures.

Great!

> What do you mean with histogram of UOPS_EXECUTED_CYCLES. There are 
> only 4 different events for cmask 1-4. You can of course add the stall and in-
> use event but for the histogram 4 counters are enough.

Although undocumented, the masks seem to work as you'd expect for higher numbers.  Since there are more than 4 execution units, one can view their utilization.  This is probably out of date as a patch, but I found this sort of thing to work:

```
diff --git a/src/includes/perfmon_skylake_events.txt b/src/includes/perfmon_skylake_events.txt
index 49eb5e2..2071eca 100644
--- a/src/includes/perfmon_skylake_events.txt
+++ b/src/includes/perfmon_skylake_events.txt
@@ -300,6 +332,10 @@ DEFAULT_OPTIONS_UOPS_EXECUTED_CYCLES_GE_3_UOPS_EXEC EVENT_OPTION_THRESHOLD=0x3
 UMASK_UOPS_EXECUTED_CYCLES_GE_3_UOPS_EXEC 0x01
 DEFAULT_OPTIONS_UOPS_EXECUTED_CYCLES_GE_4_UOPS_EXEC EVENT_OPTION_THRESHOLD=0x4
 UMASK_UOPS_EXECUTED_CYCLES_GE_4_UOPS_EXEC 0x01
+DEFAULT_OPTIONS_UOPS_EXECUTED_CYCLES_GE_5_UOPS_EXEC EVENT_OPTION_THRESHOLD=0x5
+UMASK_UOPS_EXECUTED_CYCLES_GE_5_UOPS_EXEC 0x01
+DEFAULT_OPTIONS_UOPS_EXECUTED_CYCLES_GE_6_UOPS_EXEC EVENT_OPTION_THRESHOLD=0x6
+UMASK_UOPS_EXECUTED_CYCLES_GE_6_UOPS_EXEC 0x01
 UMASK_UOPS_EXECUTED_CORE                  0x02
 DEFAULT_OPTIONS_UOPS_EXECUTED_CORE_USED_CYCLES EVENT_OPTION_THRESHOLD=0x1
 UMASK_UOPS_EXECUTED_CORE_USED_CYCLES           0x02
```

I've tried things like this for the EXECUTED, RETIRED, ISSUED, DSB, and LSD.   I think I found that it works out to 8 for all of them, but don't recall the detals right now.  Here's an example I put together showing six sustained UOP's executed and retired per cycle on Skylake that might help for testing: http://www.agner.org/optimize/blog/read.php?i=415#647.

**Comment by TomTheBear** [comment]
Thanks for the hint with the events for 5 and 6 UOPs. I will add them to the event lists for up to  "at least 6 UOPs". This should be enough for all recent architectures. I open a new issue for that.
What is really new for me is the blog on Agner's page. I visit the page quite often but I've never found the blog. Can I integrate your assembly code in likwid-bench? This would help to verify such things in the future. It's not optimal as likwid-bench works on streams of data but it should be possible somehow.

**Comment by TomTheBear** [comment]
Works for most architectures since the first related commit. For Broadwell the commit https://github.com/RRZE-HPC/likwid/commit/39fbcc915f590f66d68a135a64c67591011a4838 fixes PMC4-7. Closing issue.
