### ISSUE TITLE
[FeatureRequest] AccessD: Split out write vs read access for shared systems

### ISSUE THREAD

**Issue by pcass-epcc** [RRZE-HPC/likwid#345]
I'm a sysadmin on a system with quite a fairly diverse range of users.  The system is configured to allow single-core jobs i.e. many users might end up sharing a single node.  As such, we would not want e.g. users to change the CPU frequency of a node they are sharing.  This is easily done; we could e.g. `chmod -x` the SUID likwid-setFreq binary unless a job prologue determines a job has requested node-exclusive access, and have something in the epilogue to ensure everything is set back to default.  The issue is with the likwid-accessD binary - it encompasses both very useful read access to msr device files alongside less-used write access.

It would be useful if there was an easy way to disable write access.  This would cover almost all use-cases our users have for likwid.

Optionally, the write functionality could be split out into a separate daemon.  That way, we could still allow users who have requested node-exclusive the ability to set these, while letting all users have read-only access.  (Ideally it would also be useful if there was a simple way to reset the effects of both the -setFreq and -accessD binaries back to defaults, as I am not confident I'd be able to work out all the implications on my own)

**Comment by rupertnash** [comment]
As one of Phil's users, I'd like to support this request! Having discussed this internally, we'd guess the easy way would be to add a configure variable (e.g. `ACCESS_DAEMON_ALLOW_WRITE`) and then set a variable/macro in the source to `O_RDWR`/`O_RDONLY` based on that.

Of course, making changes to a security sensitive part of LIKWID needs careful review but we can't see any  problems here.

**Comment by rupertnash** [comment]
I've created a proof of concept here:
https://github.com/EPCCed/likwid/tree/daemon-disable-write

**Comment by TomTheBear** [comment]
We'll look into it. Thanks for the PoC.

**Comment by TomTheBear** [comment]
Can you describe the use-cases of your users in some more detail? Commonly users run `likwid-topology`, `likwid-pin`, `likwid-bench` which all require no hardware access.

**Comment by kawechel** [comment]
Our use case is that we want to use ```likwid-perfctr``` on both CPUs and GPUs

**Comment by TomTheBear** [comment]
You could restrict CPU access by using the lock file. This limits read AND write access to the CPU registers. The GPUs are not protected by this lock, admins can use the `nvidia-smi` tool to restrict GPU user measurements. 

The background of my question was more like: why read access? You cannot run `likwid-perfctr` on CPUs in read-only mode, there are always writes involved. You can run basic things like `likwid-perfctr -i` but as soon as you want to do measurements, writes to the config registers are required.

**Comment by pcass-epcc** [comment]
Thanks for all your help, this has been very useful

> You can run basic things like likwid-perfctr -i but as soon as you want to do measurements, writes to the config registers are required.

Ah, fair enough.  It sounds like that approach would be nonsensical then - we'll look to find some way to gate access conditional on a job having exclusive access to a node instead. Can I ask about node consistency? Obviously if a user has access to `likwid-setFrequencies` then we would need to make sure to reset the CPU frequency information afterwards.  Is there a similar scenario with the access daemon or is it a valid assumption that when a user's job has finished all settings are restored to their original state? If the former, do you know what we'd have to do to ensure this?

**Comment by TomTheBear** [comment]
I can describe how we handle this situation on our systems:
- We have a monitoring system in place which uses LIKWID to get metrics like memory bandwidth, FLOP rate, ... It is active for all jobs except the user wants to do own measurements.
- If the user sets the SLURM constraint `hwperf` (or PBS property `likwid`) and the job is exclusive, the owner of the lock file is changed in the prolog script. This keeps monitoring on for non-LIKWID metrics and the user has the opportunity to do measurements. In the epilog, the user is changed back to the monitoring user.
- On shared nodes, the lock user is only changed if the jobs spans the whole node. This is commonly not the case.

(I can post the short snippets out of prolog and epilog if you want. The lock file is configurable in `config.mk` at `LIKWIDLOCKPATH`.)

For `likwid-setFrequencies` there are the `-reset` and `-ureset` flags for "CPU reset" and "Uncore reset" which can be used in the epilog scripts to get back in a consistent state. We don't do that at the moment, `likwid-setFrequencies` is disabled on our production systems (we use the SLURM cpu-freq option there).

Commonly, the registers used are always left in a clean state after the measurements. LIKWID follows the PMU sharing guide released by Intel some years ago to avoid conflicts between multiple tools. In some situations (interrupted execution, `SIGKILL`, ...) the cleanup cannot run and the registers keep their content. This gets visible the next time you run LIKWID and use the same registers because LIKWID detects that the registers are still in-use. LIKWID can be forced to overwrite the registers with `--force`. I got requests for a `likwid-save-and-restore-register` utility but no work has been put into this. 

Have you thought about changing the back-end to `perf_event`? This would allow per-process measurements for core-local counters with `perf_event_paranoid=1` (shared usage). For exclusive jobs, you could reduce `perf_event_paranoid` to `0` to allow Uncore measurements. The back-end does not provide all features that are available with the access daemon because you have no register access, that's why I asked for use-cases.

**Comment by pcass-epcc** [comment]
I hadn't realised the implications of the lock file, that sounds like exactly the correct way to restrict things.

Am I correct in thinking the implications of the register cleanup not being complete are limited to only affecting profiling? i.e. it won't set anything that would affect subsequent non-likwid-using jobs?

In terms of `perf_event` - we have open questions about the security implications of lower numbers (it's not that we believe there are problems, just that it's not yet been shown that there aren't), and using the access daemon is an easy way to short-circuit the issue

I'd be interested in your prolog and epilog if you can share.  Apart from anything else, I'm not confident my logic for detecting node-exclusive (or node-spanning) jobs is resilient enough

**Comment by TomTheBear** [comment]
Yes, it's only affecting profiling (counters might keep counting) but there are no negative effects for non-likwid jobs. I heard that some events can affect the in-core execution (on Intel) but I don't know which and to what extent. I assume it's the case only in heavier tasks like PEBS/IBS which cannot be used with LIKWID (requires in-kernel support).

One idea would be to write a performance group that uses all counters (at least the commonly used ones) and do a `likwid-perfctr -C N -g RESETGROUP --force hostname` in the epilog. This shouldn't take long but you can be sure that everything is reset to normal even if a user's measurement was interrupted.

My feeling is also that the few paranoid levels are not enough to restrict the mighty perf_event interface properly. Most of the HPC centers use the perf_event backend of LIKWID. But I also know a few which use the access daemon with similar reasons.

If you have already some logic in the prolog and epilog script, you probably don't need our snippets. That's from our production system (no shared nodes):
```
if [[ "$SLURM_JOB_CONSTRAINTS" =~ "hwperf" ]] ; then
 # That's LIKWID's mechanism to limit access (only the owner of likwid.lock can use it)
 chown $SLURM_JOB_USER /var/run/likwid.lock
 # Grant permission to use performance counters via perf interface (e.g. with vtune/PAPI/LIKWID)
 echo 0 > /proc/sys/kernel/perf_event_paranoid
fi
```
```
if [[ "$SLURM_JOB_CONSTRAINTS" =~ "hwperf" ]] ; then
 chown montioringuser /var/run/likwid.lock
 echo 2 > /proc/sys/kernel/perf_event_paranoid
fi
```

**Comment by pcass-epcc** [comment]
Thanks - would you be willing to share your logic anyway?  I **know** there are race conditions in ours (this logic is used by both our prolog and epilog):
```
        if /usr/bin/scontrol -d show node ${hostname} | /usr/bin/egrep "State=(ALLOCATED|RESERVED\+COMPLETING)" >/dev/null ; then
                log Node is fully allocated to jobs
                if [ $(/usr/bin/squeue -h --nodelist=${hostname} | /usr/bin/wc -l) == 1 ]; then
                        log This is the only job on the node i.e. exclusive
```

...but I couldn't find a more elegant way

**Comment by TomTheBear** [comment]
Our shared-usage clusters uses Torque, so LIKWID is enabled with the `:likwid` property.

```
case $(hostname) in
    c0h*)       FULL="0-15" # cluster 0
                FULL_SMT="0-31"
                ;;
    c1h*)       FULL="0-3" # cluster 1
                ;;
esac
# You also could get $FULL and $FULL_SMT by parsing sysfs/procfs
if [ -f /var/run/likwid.lock ]; then
        if [ ! -e /sys/fs/cgroup/cpuset/torque/${JOBID}/cpuset.cpus -o \
             "$(cat /sys/fs/cgroup/cpuset/torque/${JOBID}/cpuset.cpus)" == "$FULL" -o \
             "$(cat /sys/fs/cgroup/cpuset/torque/${JOBID}/cpuset.cpus)" == "$FULL_SMT" ]; then
                if [[ "$REQRES" == *:likwid* ]] ; then
                        chown $USER /var/run/likwid.lock
                else
                        chown hpcop /var/run/likwid.lock
                fi
        else
                if [[ "$REQRES" == *:likwid* ]] ; then
                        echo "ATTENTION: access to performance counters can only be granted for full-node jobs"
                        echo "           however, you only got cores $(cat /sys/fs/cgroup/cpuset/torque/${JOBID}/cpuset.cpus), thus, ignoring property :likwid"
                fi
        fi
elif [[ "$REQRES" == *:likwid* ]] ; then
        echo "ATTENTION: requested access to performance counters cannot be granted as /var/run/likwid.lock does not exist or is no regular file"
fi
```

We don't use `perf_event` on these machines but you can add the `echo X > perf_paranoid` to the `chown` lines if needed.

**Comment by TomTheBear** [comment]
Any updates? further questions?

Otherwise, please close the issue. Of course, re-open it if needed.

**Comment by pcass-epcc** [comment]
Thanks very much for your help
