### ISSUE TITLE
likwid-mpirun hardcode ssh connector

### ISSUE THREAD

**Issue by axeliniyes** [RRZE-HPC/likwid#37]
The line:

`print(string.format("EXEC: %s/mpdboot -r ssh -n %d -f %s", path, nrNodes, hostfile))`

makes ssh the default connector between nodes but it shouldn't be that way, **it should be modifiable via an environment variable** because ssh is not allowed in all clusters (this was my case, in the cluster we use oarsh to connect between nodes, for security reasons ssh is prohibited)

so if someone is trying to use likwid-mpirun like that an error will occur:

`mpdboot_moonshot1-40 (handle_mpd_output 932): mpdboot: can not get anything from the mpd daemon; please check connection to moonshot2-14
mpiexec_moonshot1-40: cannot connect to local mpd (/tmp/mpd2.console_dlagunes); possible causes:`
`  1. no mpd is running on this host`
`  2. an mpd is running but was started without a "console" (-n option)`
`mpdallexit: cannot connect to local mpd (/tmp/mpd2.console_dlagunes); possible causes:`
`  1. no mpd is running on this host`
`  2. an mpd is running but was started without a "console" (-n option)`

**Comment by TomTheBear** [comment]
Thanks for your effort adjusting likwid-mpirun. Are you aware that you can fix anything that is needed to run on your architecture and add a pull request afterwards?

**Comment by TomTheBear** [comment]
Fixed in commit https://github.com/RRZE-HPC/likwid/commit/0dd7bcd415babc8c6b1eef96417730904622c9d9

**Comment by axeliniyes** [comment]
ok i might do that in the future, thanks to you too

**Comment by TomTheBear** [comment]
You're welcome. Of course I'm trying to fix all issues that are reported but since you are Lua-aware (not many people in the fields of system administration are aware of Lua) you can fix likwid-mpirun completely to make it work on your system. With a pull request afterwards we can discuss which changes are general for all systems (hostname pattern), which are somewhat system specific (oarsh as MPI starter) and what would be the best fix for the issues you addressed in the pull request.
