### ISSUE TITLE
likwid_getProcessorId wrong values

### ISSUE THREAD

**Issue by Cord3th** [RRZE-HPC/likwid#395]
**Describe the bug**
Hello there, I'm trying to reproduce a PAPI default behavior using the LIKWID API with C/C++, i. e. to measure only executing process core counters. So I'm using likwid_getProcessorId to get needed apicId for perfmon_init call. Also I call perfmon_readCounters right after perfmon_startCounters to find non-zero counters value to validate the chosen apicId. I found out that likwid_getProcessorId returns wrong apicId on several runs. For example:
```
likwid_getProcessorId() apicId is 27
perfmon_readCounters apicId is 2
Measurement result for event set INSTR_RETIRED_ANY:FIXC0 at CPU 2: 4.57939e+08
Measurement result for event set INSTR_RETIRED_ANY:FIXC0 at CPU 27: 0
```
**To Reproduce**
* LIKWID command and/or API usage:
I'm using default LIKWID API with C/C++ example.
* LIKWID version and download source (Github, FTP, package manger, ...)
FTP LIKWID 5.1.0.
* Operating system
CentOS 7
* Does your application use libraries like MPI, OpenMP or Pthreads?
No, it doesn't.
* Are you using the MarkerAPI (CPU code instrumentation) or the NvMarkerAPI (Nvidia GPU code instrumentation)?
likwid_getProcessorId only .

**Additional context**
I'm not sure if it's a bug, but could you please describe my mistakes or misunderstandings in case it's not?

**Comment by TomTheBear** [comment]
So, if I understand correctly, you want get all processors that the application is allowed to run on and use this list of processors for `perfmon_init()`?
Use this code snippet for this:
```
int insert = 0;
topology_init()
CpuTopology_t cputopo = get_cpuTopology();
int* cpulist = malloc( cputopo->activeHWThreads * sizeof(int));
// check malloc error
for (int i = 0; i < cputopo->numHWThreads; i++) {
   if (cputopo->threadPool[i].inCpuSet)
   {
       cpulist[insert] = cputopo->threadPool[i].apicId;
       insert++;
   }
}
int err = perfmon_init(insert, cpulist);
```
The important part is the check for `inCpuSet`. LIKWID reads the cpuset at startup and allows only those processors to be used later.

The use-case for `likwid_getProcessorId()` is to get the processor ID for a **pinned** process/thread. It reads the current cpuset and if the cpuset contains only a single processor, its ID is returned. If the cpuset contains more processors, it calls `sched_getcpu()`. If you have multiple processors in a cpuset, the application process/thread is free to move around the allowed processors (maybe what was happening for you). In that case, you have to add all maybe used processors to `perfmon_init()`.

I hope that resolves your issue. If I didn't understand your issue or you have further questions, feel free to ask.

**Comment by Cord3th** [comment]
Thanks for answering, but that's not what I meant. I want LIKWID to make thread-based measurements when active thread core only is in scope. Is there a way to achieve this behavior?

**Comment by moebiusband73** [comment]
Could you elaborate in more detail what exactly you want to do? Not only technically but also in general. We do not exactly understand the specific problem.

What do you mean by "when active thread core only is in scope"?

**Comment by Cord3th** [comment]
Yeah sure, let me explain the whole pipeline for better understanding.

I place a task in a queue, then it's being placed on a certain node, that consists for example of 28 cores, HWThreads in LIKWID terms as I understand.

Then it also being placed on a certain HWThread on the node, and here's the difference.

Let's say our task is on HWThread number 20. PAPI will measure only this HWThread counters by default, so my goal is to make LIKWID work in the same way.

I hope it's clear now, and I'm sorry if there're any wrong terms or smth in my explanation.

**Comment by TomTheBear** [comment]
There is a fundamental difference about the measurement method of LIKWID and PAPI. PAPI works on software process/thread basis, so you tell it to start a measurement and independent where the process runs, PAPI (or in reality `perf_event` in the kernel) follows the process, thus is independent of the HW threads. At least that's the default mode of PAPI, it probably has much more features. LIKWID, on the other hand, works on HWthreads and has no clue about application processes. LIKWID uses only a very limited set of kernel features (as long as you don't use the `perf_event` backend). LIKWID measured for example all applications running on hwthread X. PAPI would measure application Y on all hwthreads.

I checked `likwid_getProcessorId()` in a pthread-code with multiple threads reading the cpu_id additionally through `sched_getcpu()` and from `procfs`. I couldn't find any difference as long as the thread is pinned. If the threads are unpinned, they move around of course. In my short tests it also worked if the cpuset contained more than a single hwthread as long as the cpusets of the threads didn't overlap.

But I think the main issue is the way you want to do it. If you call `perfmon_init()` in every task, only the first one will actually initialize LIKWID (for the others it returns `-EEXIST`). Consequently only the hwthread list of the winning task is used for initialization and all `readCounters()` calls (independent of the calling thread) will read only the hwthreads of the winning task.
The LIKWID way-to-go would be to tell the scheduling system to initialize, setup and start the events/counters once at startup for all hwthreads and the (pinned!) tasks use only `readCountersCpu(int cpu_id)` for their HWthreads. This also reduces the overhead because `init` and `setup` are the most expensive calls in LIKWID.  But it does not allow to use different event sets in different tasks because the scheduling system is responsible and can change the eventset only for all initialized hwthreads.

I hope this answer helps you to understand how to use LIKWID in your pipeline.

**Comment by Cord3th** [comment]
Thanks a lot for your explanation.
