### ISSUE TITLE
Segfault when accessing topology->threadPool with likwid > 5.1.0

### ISSUE THREAD

**Issue by ntippman** [RRZE-HPC/likwid#410]
I use the C/C++-API to continuously measure performance data for jobs on my cluster.

Accessing the topology->threadPool data causes a segfault.

```
    CpuTopology_t topology = get_cpuTopology();
    std::vector<int> cpus;

    for (uint32_t i = 0; i < topology->numHWThreads; i++) {
        if (topology->threadPool[i].inCpuSet)     /* Sefault occurs here */
            cpus.push_back(topology->threadPool[i].apicId);
        }
    }
```

**LIKWID Release 5.1.0 seem to be working just fine, the error only occurs with release 5.1.1 and 5.2.0**

The error was tested on an i7 3930k with Ubuntu 20.04  and on a 2x Intel Xeon 6252N with AlmaLinux 8.4.

I attached a small reproducer with a makefile ([reproducer.zip](https://github.com/RRZE-HPC/likwid/files/6739728/reproducer.zip)) (with LIKWID_FORCE=1).
Execute with `./likwid <GROUP> <INTERVAL>`

**Comment by TomTheBear** [comment]
I just copied out the relevant part in a separate main function and at the moment, I see no segfault.
[main.txt](https://github.com/RRZE-HPC/likwid/files/6739988/main.txt)

Your reproducer runs just fine but your Makefile somehow has a problem, I compiled the single file manually:
`g++ -std=c++11 -Wall -pthread -DLIKWID_PERFMON $LIKWID_INC $LIKWID_LIB main.cpp -o main -llikwid`
(`$LIKWID_INC` and `$LIKWID_LIB` are set by our module system, `-DLIKWID_PERFMON` is only required for MarkerAPI which is not used in your code, so I left it out).

If I just call `make` or `make likwid`, I get `g++ -std=c++11 -Wall   -c -o main.o main.cpp`, which fails of course as it doesn't find the LIKWID header. Especially, the `-c` switch is not mentioned in the Makefile, so I assume it's taking some default rule.

As far as I remember, there was only the addition of "CPU dies" to the topology module since 5.1.0. Does any of your systems is assembled out of dies and exports die_id (in sysfs)? The `inCpuSet` field was introduced in 2014, so long time ago.

**Comment by TomTheBear** [comment]
Any updates?

**Comment by ntippman** [comment]
Sorry for the delayed response. The Makefile works fine for me and a clean reinstall of LIKWID somehow fixed the problem. As i can't reproduce the error i'm closing this issue.

Thank you

**Comment by TomTheBear** [comment]
I assume it was some version clash between the library used at build time and later at execution. Most versions are compatible but some feature might cause strange/segfaulting behavior.
