### ISSUE TITLE
Correctly support sharing uncore among multiple processes in generic read functions

### ISSUE THREAD

**Issue by ProgramFan** [RRZE-HPC/likwid#43]
When running multiple single-thread MPI processes on a single node, all processes get non-zero uncore events values (for example, memory read/write events). However, when running single MPI process with multiple threads, only NSOCKETS threads get non-zero uncore events values. Is is possible to support the same behavior in the multiple process case? This is highly demanded for single-threaded MPI applications.

**Comment by TomTheBear** [comment]
There is no global lock for multiple processes running LIKWID, only an internal one. That's why you get values for each process in the single-threaded case and NSOCKETS values for the multi-threaded case. This is one of the reasons for likwid-mpirun, it submits the Uncore events only to one CPU per socket while all the others get only the core-local counters. Using this method, you can also use plain MPI with LIKWID, just give them different event sets. There are currently no plans to have global locks.

**Comment by ProgramFan** [comment]
Thanks @TomTheBear .

I totally understand that global locks can be tricky. Controlling the eventset seems a good idea. Then how can I check if a given event is uncore or not? With this mechanism, I can then implement the idea in our home-grown framework (JASMIN), to solve the plain MPI problem.

**Comment by ProgramFan** [comment]
Good! I found them in https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid-mpirun.lua#L989.

**Comment by TomTheBear** [comment]
This is a basic check and has to be extended if one of the vendors introduces new core-local counters but in the meantime it works fine.
