### ISSUE TITLE
likwid-mpirun only returns raw data and no metrics 

### ISSUE THREAD

**Issue by DerNils-git** [RRZE-HPC/likwid#461]
I wanted to profile multiple mpi processes (openmpi/4 with slurm batch system) using likwid 5.1.0 with likwid-markers.\
(commit: 233ab943543480cd46058b34616c174198ba0459)

`likwid-mpirun -pin S0:0-9_S0:10-19_S1:20-29_S1:30-39 -m -g MEM_DP -O -mpi slurm ./myProgram`
This call returns 4 files `.output_<other_id>_<proc_id>_<hostname>.csv` only containing the Region `Group 1 Raw` for all markers.

The regions `Group 1 Metric`, `Group 1 Metric STAT` and `Group 1 Raw STAT` are missing.

**Comment by TomTheBear** [comment]
This is as intended. The metric evaluation is done by `likwid-mpirun` based on the raw values in the `.output_*` files. 

The reason:
When `likwid-mpirun` should start multiple MPI processes inside an affinity domain (e.g. CPU socket for MEM measurements like `S0:0-9_S0:10-19`), it splits up the eventset so that only one hardware thread out of the multiple MPI processes reads the Uncore unit (likely `S0:0` in your case) while all others measure only the hwthread-local events (Flops events, cycle counter, ...). So, the under the hood executed `likwid-perfctr` does not know that there are any metrics to calculate.

**Comment by DerNils-git** [comment]
Thanks for the quick explanation.

Is it possible get the retrieve metrics from the `.output_*` files somehow? I am not sure how to convert the counters into metrics myself.

**Comment by TomTheBear** [comment]
At the moment, there is no pre-defined way to evaluate the output files afterwards. But it's only Lua, so it shouldn't be a big problem to glue something together.

There are two output file readers for [normal measurements](https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid-mpirun.lua#L1599-L1685) and [MarkerAPI measurements](https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid-mpirun.lua#L1687-L1808). Finally, all results are evaluated and printed with [printMpiOutput](https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid-mpirun.lua#L1857-L2012). It contains the logic for evaluating metrics:
- Create `counterlist`: countername -> value table like `counterlist["PMC0"] = 12345`
- Get metric formula from the group:
`gdata = likwid.get_groupdata("MEM_DP"); formula = gdata["Metrics"][metric_idx]["formula"]`
- Calculate result: `likwid.calculate_metric(formula, counterlist)`

**Comment by DerNils-git** [comment]
Thanks this should work.
