### ISSUE TITLE
likwid-perfctr fails to fork when using the marker API and large amounts of memory

### ISSUE THREAD

**Issue by K-Wic** [RRZE-HPC/likwid#53]
Hi,

I ran into the problem that I could run a large simulation when using plain likwid-perfctr, but using the marker API would fail.
By now I figured out it is due to the call to fork() when calling the marker for the first time and which fails with an errno of ENOMEM. This is caused by the fact that the forked process inherits the resources from the parent process, including the memory consumption. Since the markers are called well into the simulation, I have already allocated a lot of memory and fork now tries to reserve the same amount for each child processes, which naturally fails.
I tried to work around this problem by calling LIKWID_MARKER_REGISTER early on, but unfortunately this does not cause forking. As another workaround I called MARKER_START and MARKER_STOP in quick succession and it does lead to the expected/hoped for behavior and hopefully does not mess with the results too much.

This is the solution I am currently going with, but maybe there is a better way?
Perhaps the REGISTER call could be changed to handle the forking and maybe give the user a hint when the forking fails due to ENOMEM?

Also I came across two other problems while debugging this.

1) Turning on the debug mode in config.mk does not disable the gcc optimizations, which makes the use of gdb impossible. I have submitted a pull request which addresses this (#52).
(Additionally, calling gdb on all the lua stuff is not exactly trivial, so I give an example here in the hopes that no one else ever needs it: "gdb --args likwid-lua /usr/bin/likwid-perfctr -g xxx -C xxx ./executable" and creating the breakpoints depending on future loads of libraries)

2) There is an error message when fork fails, but likwid does not abort, but instead fails when it cannot open the socket in /tmp/likwid--1. The -1 is the pid of the forked process...
I therefore propose the following change:

```
diff --git a/src/access_client.c b/src/access_client.c
--- a/src/access_client.c
+++ b/src/access_client.c
@@ -151,7 +151,8 @@ access_client_startDaemon(int cpu_id)
     }
     else if (pid < 0)
     {
-        ERROR_PLAIN_PRINT(Failed to fork);
+        ERROR_PRINT(Failed to fork while starting client for cpu %d, cpu_id);
+        exit(EXIT_FAILURE);
     }

     EXIT_IF_ERROR(socket_fd = socket(AF_LOCAL, SOCK_STREAM, 0), socket() failed);
```

This ensures that likwid aborts right away and it also prints the reason for the fork failure.

MfG
K-Wic

**Comment by TomTheBear** [comment]
Hi,
So, the first problem would be resolvable if the forks would happen early in your application? If your application doesn't have huge amounts of memory allocated, it couldn't be inherited to the forked process. But, I know, this is just an inconvenient workaround. My suggestion would be to run MARKER_INIT and some empty region (in parallel) directly at the beginning of your application. With the parallel START/STOP, the processes are forked. Originally, the threads were started at MARKER_INIT but always one process per CPU and if your code runs only on a single CPU there are way to many forks. For normal systems with a few hardware threads this is not problematic but e.g. a KNL with >250 hardware threads has to fork a lot. Therefore, the behavior was changed to start only a single process in the beginning and as soon as LIKWID realizes that it is used in a threaded context, it starts the required processes. REGISTER is not enough here because it just creates the hash table entries but performs no access to the registers which triggers the fork.

To 1.)
I declined your pull request but added the same functionality in https://github.com/RRZE-HPC/likwid/commit/cb17cb251235f0cd8ffd0be9e3d7ee50a05872f2. I can understand that debugging with LIKWID in combination is not easy, especially when you have to use a specific executable. 

To 2.)
In the old times, an ERROR_PRINT contained a return -1 but this was changed as most of the return codes were never checked and therefore meaningless. Now, it is in the responsibility of the developer (blame on me) to handle it properly. A simple `return -1` results in the following error messages:
```
$ likwid-perfctr -C 0,1,2 -g L3 hostname
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
CPU type:	Intel Core Haswell processor
CPU clock:	3.39 GHz
ERROR - [./src/access_client.c:access_client_startDaemon:155] Failed to fork
ERROR - [./src/access_client.c:access_client_init:213] Bad file descriptor.
Start of access daemon failed for CPU 0
ERROR - [./src/perfmon.c:perfmon_init:1335] Cannot get access to performance counters
```
The advantage is that LIKWID can free all the allocated memory before exiting. I know the OS does it at exit but if you use LIKWID inside your code, do you really want your application to get killed or to get the exit code and avoid further calls to LIKWID? 

Greetings,
Thomas

**Comment by K-Wic** [comment]
Hi,
the workaround you suggested is what I am currently using:
```
LIKWID_MARKER_INIT;
#pragma omp parallel
{
  LIKWID_MARKER_THREADINIT;
}
#pragma omp parallel
{
  LIKWID_MARKER_START("regionA");
  LIKWID_MARKER_STOP("regionA");
  LIKWID_MARKER_START("regionB");
  LIKWID_MARKER_STOP("regionB");
}
```
I just thought, that it would be nice to spare others all the debugging work by having REGISTER handle this. Especially since the register call is advertised as optional, but helpful in case of performance issues (yes, different issues, but still somewhat similar).

To 1): Thanks.

To 2): I am not sure I get what you are saying, but let me explain what I suggested in a bit more detail.
The error I originally got was:
```
--------------------------------------------------------------------------------
ERROR - [./src/access_client.c:access_client_startDaemon:154] Failed to fork
ERROR - [./src/access_client.c:181] No such file or directory
Exiting due to timeout: The socket file at '/tmp/likwid--1'                 could not be opened within 10 seconds.
Consult the error message above this to find out why.
If the error is 'no such file or directoy',                 it usually means that likwid-accessD just failed to start.
--------------------------------------------------------------------------------
```
and there are two problems I have with this: Firstly, I do not know why it failed to fork and I think the info, that it was due to memory requirements would have been helpful. Hence the suggested change from ERROR_PLAIN_PRINT to ERROR_PRINT.
Secondly the message about the missing file or directory is misleading. If the fork failed, there is really no reason to wait for the socket, ... and fail. That is why I suggested exit(EXIT_FAILURE). Maybe that is not the appropriate action, but when I get an error I expect the application to terminate and it will anyways, since not finding the socket causes likwid to terminate.

For reference: the output after the changes:
```
--------------------------------------------------------------------------------
CPU name:	Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
CPU type:	Intel Xeon Broadwell EN/EP/EX processor
CPU clock:	2.60 GHz
--------------------------------------------------------------------------------
ERROR - [./src/access_client.c:access_client_startDaemon:154] Cannot allocate memory.
Failed to fork while starting client for cpu 25
ERROR - [./src/access_client.c:access_client_startDaemon:154] Cannot allocate memory.
Failed to fork while starting client for cpu 4
--------------------------------------------------------------------------------
```
MfG
K-Wic

**Comment by TomTheBear** [comment]
Hi,

you just need one Start/Stop pair in the parallel region, the forking is triggered by the Start call. And it doesn't need to be one of your actual region names. I use 'empty' for such regions because even a start/stop pair without code change the hardware counters and consequently your region results. It shouldn't be problematic to trigger the forks at Register. I'm currently thinking about using clone() instead of fork() to reduce the inherited features.

Fork at register():
```
diff --git a/src/libperfctr.c b/src/libperfctr.c
index cf6d637..0dccf37 100644
--- a/src/libperfctr.c
+++ b/src/libperfctr.c
@@ -429,7 +429,7 @@ likwid_markerRegisterRegion(const char* regionTag)
     bcatcstr(tag, groupSuffix);
     int cpu_id = hashTable_get(tag, &results);
     bdestroy(tag);
-    return 0;
+    return HPMaddThread(cpu_id);
 }
 
 int
```

To 2.) The only thing I wanted to say is that an exit is too drastic in that case. A simple `return -1` has the same effect but we have time to clean everything (I now use fork()'s error code instead of -1). The error message can be more expressive, that's true. 

The problem with your change is, that the counters are still running when LIKWID exists. Next time LIKWID starts, it will probably inform you that some counters are in use and you should set `--force`. If we only return from that function, we can execute stopCounters() and finalize(). This is done by likwid-perfctr and not the MarkerAPI. The daemon for likwid-perfctr is started directly at the beginning, so this one was able to fork and to setup/start the counters in your case. The same daemon is used to stop and clear them in the end. I have to see how the graceful exit and print a meaningful message. The current state looks like this (imitating your case where perfctr works but MarkerAPI fails to start access clients):
```
$ likwid-perfctr -C 0,1,2 -g L3 -m  test/streamGCC 
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
CPU type:	Intel Core Haswell processor
CPU clock:	3.39 GHz
--------------------------------------------------------------------------------
Using likwid
ERROR - [./src/access_client.c:access_client_startDaemon:168] Cannot allocate memory.
Failed to fork access daemon for CPU 0
ERROR - [./src/perfmon.c:perfmon_init:1336] Cannot get access to performance counters
-------------------------------------------------------------
Number of Threads requested = 3
Thread 0 running on processor 0 ....
Thread 2 running on processor 2 ....
Thread 1 running on processor 1 ....
Processed 640.0 Mbyte at copy benchmark in 0.0446 seconds: 14359.89 MByte/s
Processed 1280.0 Mbyte at triad benchmark in 0.0737 seconds: 17368.53 MByte/s
--------------------------------------------------------------------------------
Marker API result file does not exist. This may happen if the application has not called LIKWID_MARKER_CLOSE.
```
You get a better error message, your application still runs and the counters are reset in the end so no `--force` at the next run. It's not committed yet, I have to do some further checks first.

Greetings,
Thomas

**Comment by TomTheBear** [comment]
So, this is seems fixed. The threads are started at likwid_markerRegisterRegion or at the first likwid_markerStartRegion.
