### ISSUE TITLE
Marker results are difficult to read at a glance

### ISSUE THREAD

**Issue by nkurz** [RRZE-HPC/likwid#61]
I'm finding the fancy formatting of the marker results to make the numbers difficult to interpret.  The automatic centering makes the table look pretty, but it makes it more difficult to compare the magnitude of the numbers at a glance.   I'm frequently finding myself counting the digits trying to figure out whether one number is 1/10 of another, or 1/100.   

For example, rather than this with the centering: 

```
+---------------------------+---------+--------------+
|           Event           | Counter |    Core 16   |
+---------------------------+---------+--------------+
|    Runtime (RDTSC) [s]    |   TSC   | 8.833629e-01 |
|     RS_FULL_STALL_ALL     |   PMC0  |    2132399   |
| NO_ALLOC_CYCLES_RAT_STALL |   PMC1  |   136345931  |
|     INSTR_RETIRED_ANY     |  FIXC0  |  1920997053  |
|   CPU_CLK_UNHALTED_CORE   |  FIXC1  |  1141587342  |
|    CPU_CLK_UNHALTED_REF   |  FIXC2  |  1141587369  |
+---------------------------+---------+--------------+
```

I would find something like this to be faster to compare with similar regions:

```
+---------------------------+---------+--------------+
|           Event           | Counter |    Core 16   |
+---------------------------+---------+--------------+
| Runtime (RDTSC) [s]       |    TSC  |    0.8833629 |
| RS_FULL_STALL_ALL         |   PMC0  |      2132399 |
| NO_ALLOC_CYCLES_RAT_STALL |   PMC1  |    136345931 |
| INSTR_RETIRED_ANY         |  FIXC0  |   1920997053 |
| CPU_CLK_UNHALTED_CORE     |  FIXC1  |   1141587342 |
| CPU_CLK_UNHALTED_REF      |  FIXC2  |   1141587369 |
+---------------------------+---------+--------------+
```

This is probably personal preference, and I don't expect to convince anyone else that one way is better, but where in the code would I find the formatting code to try out some variations?

**Comment by TomTheBear** [comment]
I can understand that you want the results aligned and in non-exponential format. The printing of the table is performed by the [printtable function in likwid.lua](https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid.lua#L340). Moreover, the spaces in front and rear of the numbers are determined in [Line 375 by the get_spaces function](https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid.lua#L375). Tune as much as you want, that's one of the reasons why LIKWID uses a scripting language as frontend since 4.0.
