### ISSUE TITLE
Question: when `likwid-powermeter a.out`, does it measure the power consumption of the whole CPU or just of `a.out`?

### ISSUE THREAD

**Issue by Sunt-ing** [RRZE-HPC/likwid#617]
I did not find the answer in the doc or issue list. Thanks for answering in advance!

**Comment by Sunt-ing** [comment]
Thanks for your reply! 

I got the following output, and I guess it means: my application used two CPUs (CPU 0 and CPU 10); during the running, CPU 0 consumed 3364.62 J; CPU 10 consumed 5068.51 Joules. 

Is my understanding correct? Thanks for your help!

Machine configuration: Two Intel Xeon Silver 4114 10-core CPUs at 2.20 GHz.


```
Runtime: 100.139 s
Measure for socket 0 on CPU 0
Domain PKG:
Energy consumed: 3364.62 Joules
Power consumed: 33.5996 Watt
Domain PP0:
Energy consumed: 0 Joules
Power consumed: 0 Watt
Domain DRAM:
Energy consumed: 1378.37 Joules
Power consumed: 13.7646 Watt
Domain PLATFORM:
Energy consumed: 0 Joules
Power consumed: 0 Watt

Measure for socket 1 on CPU 10
Domain PKG:
Energy consumed: 5068.51 Joules
Power consumed: 50.615 Watt
Domain PP0:
Energy consumed: 0 Joules
Power consumed: 0 Watt
Domain DRAM:
Energy consumed: 605.982 Joules
Power consumed: 6.05144 Watt
Domain PLATFORM:
Energy consumed: 0 Joules
Power consumed: 0 Watt
```

**Comment by TomTheBear** [comment]
Your system has two CPU sockets. Since the energy units exist only once per socket, one CPU per socket is selected to measure the energy stuff. In your case, that's CPU 0 and CPU 10. The IDs for the CPUs are less important, more important is socket 0 and socket 1.

> my application used two CPUs (CPU 0 and CPU 10); during the running, CPU 0 consumed 3364.62 J; CPU 10 consumed 5068.51 Joules.

My system has two CPUs (socket 0 and socket1); during the running, all cores of socket 0 consumed 3364.62 J; all cores of socket 1 consumed 5068.51 Joules. Moreover, the memory DIMMs attached to socket 0 consumed 1378.37 J, the memory DIMMs attached to socket 1 consumed 605.982 J.

(`PKG` domain = all cores of the socket, `DRAM` domain = all memory DIMMs of the socket)

**Comment by TomTheBear** [comment]
I added more text to the `likwid-powermeter` wiki page. Can you please check whether it explains it now. If not, feedback is appreciated.

**Comment by Sunt-ing** [comment]
Thanks for your answer! Now I know the meaning exactly. 

Another question is now I want to do scheduling based on the output information. My scheduler is supposed to be written in Python, so it looks like the best way is to read the output text and then manually parse them, right? Thanks for your help!

**Comment by Sunt-ing** [comment]
My scheduling is to change knobs like power limit based on the energy consumption in this computer (2 CPU + 1 GPU). Thanks for your kind help again!

**Comment by TomTheBear** [comment]
For changing knobs, I recommend using the experimental sysfeatures component introduced with 5.3.0. The old/current APIs do not provide knobs for setting a power limit. You have to explicitly enable sysfeatures before the build (`BUILD_SYSFEATURES=true` in `config.mk`). Unfortunately, there is no support in pylikwid yet but creating it wouldn't be much work. Of course, you could also use the corresponding CLI app `likwid-sysfeatures` but changes in the output might require updates of your parser.

The sysfeatures component is the new way to get the energy data. Additionally, it provides the knobs like power limits. `likwid-powermeter`, `likwid-setFrequencies` and `likwid-features` will be deprecated in the future because all those features will be provided by `likwid-sysfeatures`.

The sysfeatures component is still under development, so if you want to join the effort, let me know.

**Comment by Sunt-ing** [comment]
I will take a look and use them. Thanks for your careful and informative explanation!

**Comment by TomTheBear** [comment]
Can we close the issue?

**Comment by Sunt-ing** [comment]
Sure. Thanks!
