### ISSUE TITLE
likwid-bench uses mismatching array sizes to compute results

### ISSUE THREAD

**Issue by hofm** [RRZE-HPC/likwid#63]
There's a mismatch between the dataset size used in benchmarks and the dataset size used to compute the benchmark results which can lead to significantly off results.

Example:
./likwid-bench -t my_benchmark -w N:10kB:1
My loop stride is 512. Data type is SINGLE.
The loop limit is set to 2048 instead of 2500 (10000/sizeof(float = 2500).
The results are calculated as follows:
 cycPerUp = ((double) maxCycles / (double) (threads_data[0].data.iter * realSize));
with realSize is the user-supplied 10000B.
The reported measurement in this case is off by about 20%!

**Comment by hofm** [comment]
Inner loop executions wrong as well (uses realSize).

**Comment by TomTheBear** [comment]
The described problem is exactly the other way round. The loop limit is set to 2048 but when the loop reaches 2048 it executes one more iteration. Consequently, with a loop stride of 512, you traverse 2560 elements. This is doesn't lead to a segfault because the vectors are always allocated a little bit larger as requested. I also checked the inner loop executions and they are right.
But nevertheless, I did some corrections. The vector size is reduced to fit the loop stride and thread count because when the loop body is unrolled we cannot execute only a part of the body. If likwid-bench has to reduce them, a warning is printed. All final calculations are based on the corrected size.
