### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by tnibler** [RRZE-HPC/likwid#636]
Hi, thank you for your work first of all. Version 5.3.0 is coming up on 11 months old now, so packages in all kinds of repositories are really far behind and missing out on tons of new development. 

Would it be possible to get a new release out? Does not even have to be current master, just some of the recent new hardware would be very useful.

Thanks!

**Comment by TomTheBear** [comment]
Thanks for the request, I have been and will be busy with other projects. I didn't find time to put out a bugfix release for 5.3 although it would have been good since 5.3.0 contains some unfortunate bugs. New hardware is only introduces in major releases, so 5.4.x which requires more effort than a bugfix release.

I saw you created a MarkerAPI package for Rust. Thanks for that. Is it tested/mature enough to be listed in the LIKWID wiki?

**Comment by tnibler** [comment]
I see, it's not that big of a deal anyway since it's easy to build from source.

The Rust library is just basic bindings so not much to go wrong, definitely feel free to add it to the wiki :)

**Comment by TomTheBear** [comment]
https://github.com/RRZE-HPC/likwid/releases/tag/v5.4.0
