### ISSUE TITLE
Fails to build on ppc

### ISSUE THREAD

**Issue by chuckatkins** [RRZE-HPC/likwid#69]
Using a Power 8 running Fedora 21 with gcc 4.9.2:
```
$ uname -r
3.17.4-301.fc21.ppc64le
$ gcc --version
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
```

First, just trying to build unchanged out of a git/master clone:
```
$ make
...
===>  COMPILE  GCC/perfmon.o
./src/perfmon.c: In function ‘perfmon_addEventSet’:
./src/perfmon.c:1549:13: error: ‘PerfmonEventSet’ has no member named ‘regTypeMask’
     eventSet->regTypeMask = 0x0ULL;
```
So to continue past that:
```
$ make -k
...
===>  COMPILE  GCC/topology_proc.o
In file included from ./src/topology_proc.c:36:0:
./src/topology_proc.c: In function ‘proc_init_cpuFeatures’:
./src/includes/cpuid.h:46:5: error: impossible register constraint in ‘asm’
     __asm__ volatile(".ifnc %%ebx,%3 ; movl  %%ebx,%3 ; .endif  \n\t" \
     ^
...
```
And then there's a whole slew of errors for the benchmarks trying to compile and assemble the x86 files,which obviously will not work on ppc.

**Comment by TomTheBear** [comment]
The current master branch does not have POWER8 support. There is a pull request (https://github.com/RRZE-HPC/likwid/pull/67) that introduces POWER8 support. If you have applied that, please choose compiler GCCPOWER in config.mk but it doesn't seem like it because regTypeMask is removed by the pull request. The pull request is still under development. The compiler setting GCCPOWER also sets the proper path to the benchmarks for POWER8 chips.
