### ISSUE TITLE
build against externally provided hwloc, lua (use Autotools/CMake)

### ISSUE THREAD

**Issue by davydden** [RRZE-HPC/likwid#71]
from `INSTALL` file it appears that `likwid` depends on `hwloc` and `lua`, however I could not fid a way to use externally provided `hwloc` and `lua`. I think it would be good if the way to do this is documented.

It would be even better if `likwid` would use `Autotools` or `CMake` to build. Then one would not need to edit make files to provide paths/link flags for dependencies and turn off/on their build.

The fact that 

> If external libraries are used, they are shipped with Likwid. 

could lead to undesired surprises if one uses `likwid` as a dynamic library in another code which itself at some point (perhaps through dependencies) is also linked against `hwloc` and `lua`.

**Comment by TomTheBear** [comment]
There is no way to use an externally provided `hwloc` with LIKWID. The reason is that the `hwloc` functions are prefixed during build with `likwid_`. To use an external `hwloc` you need to patch the LIKWID source to use the original `hwloc` function names. Moreover, the included `hwloc` contains extra functionality, e.g. provides cache inclusiveness, and I don't know whether this is part of the default `hwloc` releases in the meantime. The functionality was added by the hwloc team itself for LIKWID so it is likely that they add it to the default source as well.
The internal `lua` can be replaced with externally provided `lua` but there is no documentation how to do it. You can check the source files in [repos at FTP@FAU](ftp://ftp.rrze.uni-erlangen.de/mirrors/likwid/repos/) which was my first attempt to use system `lua`.

The build system is based on `make` to keep the build dependencies minimal. Moreover, most of the paths/links are used only internally and need only little adjusting in most cases. To turn features on/off, you can also use the command line: `make PREFIX=/some/where DEBUG=true` . I can understand that many project use more sophisticated build systems but for LIKWID `make` is enough.

Since the function of `hwloc` are prefixed, there shouldn't be any problems when a code depends itself on another `hwloc`. For `lua` you might get problems.

**Comment by davydden** [comment]
> Since the function of hwloc are prefixed, there shouldn't be any problems when a code depends itself on another hwloc

agreed. Thanks for clarification. May I suggest adding the explanation above to the readme/INSTALL or alike  in some shape/form?

> The internal lua can be replaced with externally provided lua but there is no documentation how to do it.  

do you mind documenting it? I added `likwid` to Spack, see https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/likwid/package.py

Fixing external dependency on `lua` to avoid suprises would be good to have.

> For lua you might get problems.

exactly my point! 


> I can understand that many project use more sophisticated build systems but for LIKWID make is enough.

fair enough.

**Comment by TomTheBear** [comment]
I'll add a section in the INSTALL file.

> > The internal lua can be replaced with externally provided lua but there is no documentation how to do it.

> do you mind documenting it? I added likwid to Spack, see https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/likwid/package.py

Many thanks for integrating it in Spack.
As you could see in the source package files on the FTP I tried it. In most cases I needed to patch the internal Lua interface because many distributions don't provide Lua 5.3. Most packages get built but they don't work. I currently don't have the time to put further effort into this but this issue will always remind me to do it.

**Comment by davydden** [comment]
> As you could see in the source package files on the FTP I tried it. In most cases I needed to patch the internal Lua interface because many distributions don't provide Lua 5.3.

could you point me to the patches, i would then try to port them? Frankly i have no experience in packaging anything for Ubuntu, thus it was not obvious for me from the links above.

**Comment by TomTheBear** [comment]
I don't know the way to extract them from deb files, but here is a way for the source RPMs.
```
$ mkdir /tmp/likwid-src-rpm && cd /tmp/likwid-src-rpm 
$ wget ftp://ftp.rrze.uni-erlangen.de/mirrors/likwid/repos/ScientificLinux_7/src/likwid-4.1.2-6.1.src.rpm
$ rpm2cpio likwid-4.1.2-6.1.src.rpm
$ ls *lua*.patch
likwid-change-path-for-lua-helper.patch
likwid-lua-no-unsigned.patch
likwid-with-system-lua.patch
```

Comment on the packages at ftp://ftp.rrze.uni-erlangen.de/mirrors/likwid/repos for all:
They are my attempt to provide packages for a bunch of operating systems. As noted above I have no clue whether they work. I only got them to build. For some operating systems there exist maintained packages (thanks), please use them.

**Comment by davydden** [comment]
i see, thanks, will give it a try...

**Comment by davydden** [comment]
If anyone will also be looking at this thread, here are the ScientificLinux patches (thanks @TomTheBear ): 

[likwid-lua-patches.zip](https://github.com/RRZE-HPC/likwid/files/642534/likwid-lua-patches.zip)

I quickly looked through them and I am not sure if it is easier to keep patching Likwid or actually extend make files properly to allow external `lua`. Will give it another look next week.

**Comment by davydden** [comment]
another link to Debian patches: https://anonscm.debian.org/cgit/likwid/likwid.git/tree/debian/patches/10-debianize.patch

**Comment by TomTheBear** [comment]
Fixed with pull request https://github.com/RRZE-HPC/likwid/pull/72
The pull request enables building against a system provided Lua.

**Comment by TomTheBear** [comment]
Can we close this issue? LIKWID supports getting built against system provided Lua. Currently no efforts to do that for hwloc as well as the LIKWID internal one does some more than the common hwloc versions.

**Comment by davydden** [comment]
sure, let's close this.
