### ISSUE TITLE
likwid-pin: Wrong affinity mask when running single-threaded with multiple cores in pin mask

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/likwid#99]
$ env OMP_NUM_THREADS=2 likwid-pin -s 0x0  -c S0:0-9 ./a.out

works as intended: the first thread has a mask of 1 and the second has a mask of 2. However,

$ env OMP_NUM_THREADS=1 likwid-pin -s 0x0  -c S0:0-9 ./a.out

leads to an affinity mask of 0x3ff, i.e., the thread is free to move within the pin mask specified.

likwid-perfctr with -C shows the same behavior.

Tested with likwid 4.2.0.

**Comment by TomTheBear** [comment]
Fixed in https://github.com/RRZE-HPC/likwid/commit/bd0da906b4a20f192e18faec6548edf03bc4fef7 and https://github.com/RRZE-HPC/likwid/commit/0d84175ed7d55c8a1341d94d74ab8b65e07ce36b
```
$ OMP_NUM_THREADS=1 likwid-pin -c N:1-3 -s 0x0 test/print_cpuset
Environment variable OMP_NUM_THREADS already set to 1 but 3 cpus required
[likwid-pin] Main PID -> core 1 - OK
$ OMP_NUM_THREADS=2 likwid-pin -c N:1-3 -s 0x0  test/print_cpuset
Environment variable OMP_NUM_THREADS already set to 2 but 3 cpus required
[pthread wrapper] 
[pthread wrapper] MAIN -> 1
[pthread wrapper] PIN_MASK: 0->2  1->3  
[pthread wrapper] SKIP MASK: 0x0
	threadid 140230172878592 -> core 2 - OK
```
I also checked likwid-perfctr. If less threads than given in the CPU string are used, the output tables are adjusted accordingly.
